
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-06-06T13:50:32+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "a83b98b022dfb3b27fec10ef85d4798139e57e21",
 "version": "0.20.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
