"""
standard warnings and errors builtins
Author: Haokun Zhang <haokun.zhang@hirain.com>
character: strict root script
"""

# warnings
class BaseWarn(Warning):...
class PackageWarn(BaseWarn):...
class InternalWarning(PackageWarn):...
class DependencyWarning(PackageWarn):...
class DependencyIncompatibleWarning(DependencyWarning):...
class TestTimeWarning(BaseWarn):...


# errors
class BaseError(Exception):...
class PackageErr(BaseError):...
class InternalError(PackageErr):...
class DependencyError(PackageErr):...
class DependencyIncompatibleError(DependencyError):...
class VersionError(PackageErr):...
class TestTimeError(BaseError):...
class InstanceError(BaseError):...
class InvalidArgumentError(BaseError):...
