
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-06-05T07:13:56+0200",
 "dirty": true,
 "error": null,
 "full-revisionid": "4b8efb697a0b4aaafcfb22697eb71779a312b92d",
 "version": "0.1.17"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
