# coding: utf-8

"""
    Montelo

    Documentation for the Montelo API.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from montelo.client.openapi_client.api.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DefaultApi()

    def tearDown(self) -> None:
        pass

    def test_webhook_controller_clerk_get_webhook(self) -> None:
        """Test case for webhook_controller_clerk_get_webhook

        """
        pass

    def test_webhook_controller_clerk_post_webhook(self) -> None:
        """Test case for webhook_controller_clerk_post_webhook

        """
        pass

    def test_webhook_controller_stripe_post_webhook(self) -> None:
        """Test case for webhook_controller_stripe_post_webhook

        """
        pass


if __name__ == '__main__':
    unittest.main()
