# coding: utf-8

"""
    Montelo

    Documentation for the Montelo API.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from montelo.client.openapi_client.api.datapoint_run_api import DatapointRunApi


class TestDatapointRunApi(unittest.TestCase):
    """DatapointRunApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DatapointRunApi()

    def tearDown(self) -> None:
        pass

    def test_datapoint_run_controller_create_datapoint_run(self) -> None:
        """Test case for datapoint_run_controller_create_datapoint_run

        """
        pass

    def test_datapoint_run_controller_get_datapoint_with_experiment(self) -> None:
        """Test case for datapoint_run_controller_get_datapoint_with_experiment

        """
        pass

    def test_datapoint_run_controller_update_datapoint_run(self) -> None:
        """Test case for datapoint_run_controller_update_datapoint_run

        """
        pass


if __name__ == '__main__':
    unittest.main()
