
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-06-04T16:02:02-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "ecd6703d29e227a0204fc15bb6f03aef33fc31ff",
 "version": "4.2.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
