
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-06-07T10:01:03+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "c7fad54f34b63408eff2001d3f2ea16be7af79a4",
 "version": "1.1.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
