
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-06-07T11:34:45-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "c2a8c754f5e362fcd4d68857b83c2edf1bc1f5d0",
 "version": "4.2.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
