#ifndef NETGEN_VERSION_HPP_INCLUDED
#define NETGEN_VERSION_HPP_INCLUDED
#define NETGEN_VERSION "6.2.2403-38-geed9aa8e"
#define NETGEN_VERSION_MAJOR 6
#define NETGEN_VERSION_MINOR 2
#define NETGEN_VERSION_PATCH 2403
#define NETGEN_VERSION_TWEAK 38
#define NETGEN_VERSION_HASH "geed9aa8e"
#endif // NETGEN_VERSION_HPP_INCLUDED
