
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-06-05T16:21:35+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "e249fee80342c394c551ba1b034a347798261f39",
 "version": "0.3.49"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
