
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-06-07T00:15:12+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "4bb462eb1bc105e0bb157d4ef7e72c1e2d9ceb98",
 "version": "1.25.0.post0.dev213"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
