# coding: utf-8
# file generated by setuptools_scm + setup.py
# don't change, don't track in version control
git_hash = b'\x9dR=\xd2'
full_git_hash = '9d523dd21ef7615aa877d576b948881f2e159f25'
git_branch = 'HEAD'
dirty = False
