# Generated by Django 4.1.6 on 2023-07-27 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "django_ticketbai",
            "0009_alter_config_options_alter_invoice_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="signature_value",
            field=models.CharField(
                blank=True, max_length=400, null=True, verbose_name="Signature Value"
            ),
        ),
    ]
