# Generated by Django 4.1.6 on 2024-05-21 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_ticketbai", "0013_invoice_vat_breakdown_alter_invoice_pre_invoice"),
    ]

    operations = [
        migrations.AddField(
            model_name="config",
            name="logo",
            field=models.CharField(
                blank=True,
                help_text="Relative path to the logo",
                max_length=150,
                null=True,
                verbose_name="Logo",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="Eposta"
            ),
        ),
    ]
