# Form implementation generated from reading ui file '/tmp/tmpl3te6bps/jdMacroPlayer-0.2/jdMacroPlayer/ui/SelectKeyDialog.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_SelectKeyDialog(object):
    def setupUi(self, SelectKeyDialog):
        SelectKeyDialog.setObjectName("SelectKeyDialog")
        SelectKeyDialog.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(SelectKeyDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.search_edit = QtWidgets.QLineEdit(parent=SelectKeyDialog)
        self.search_edit.setObjectName("search_edit")
        self.verticalLayout.addWidget(self.search_edit)
        self.key_list = QtWidgets.QListWidget(parent=SelectKeyDialog)
        self.key_list.setObjectName("key_list")
        self.verticalLayout.addWidget(self.key_list)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ok_button = QtWidgets.QPushButton(parent=SelectKeyDialog)
        self.ok_button.setObjectName("ok_button")
        self.horizontalLayout.addWidget(self.ok_button)
        self.cancel_button = QtWidgets.QPushButton(parent=SelectKeyDialog)
        self.cancel_button.setObjectName("cancel_button")
        self.horizontalLayout.addWidget(self.cancel_button)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(SelectKeyDialog)
        QtCore.QMetaObject.connectSlotsByName(SelectKeyDialog)

    def retranslateUi(self, SelectKeyDialog):
        _translate = QtCore.QCoreApplication.translate
        SelectKeyDialog.setWindowTitle(_translate("SelectKeyDialog", "Select key"))
        self.search_edit.setPlaceholderText(_translate("SelectKeyDialog", "Search"))
        self.ok_button.setText(_translate("SelectKeyDialog", "OK"))
        self.cancel_button.setText(_translate("SelectKeyDialog", "Cancel"))
