from setuptools import setup, find_packages

setup(
    name='DocTableFlow',
    version='0.1.5',
    author='Rohit Sahoo',
    author_email='rohitsahoo741@gmail.com',
    description='Fetch Tables from the documents',
    packages=find_packages(),
    install_requires=[
        'cffi',
        'chardet',
        'charset-normalizer',
        'contourpy',
        'cryptography',
        'cycler',
        'Deprecated',
        'deprecation',
        'et-xmlfile',
        'fonttools',
        'img2pdf',
        'importlib_resources',
        'joblib',
        'kiwisolver',
        'lxml',
        'markdown-it-py',
        'mdurl',
        'numpy',
        'ocrmypdf',
        'packaging',
        'pandas',
        'pdfminer',
        'pdfminer.six',
        'pikepdf',
        'pillow',
        'pluggy',
        'pycparser',
        'pycryptodome',
        'Pygments',
        'pyparsing',
        'pypdf',
        'PyPDF2',
        'python-dateutil',
        'pytz',
        'reportlab',
        'rich',
        'scikit-learn',
        'scipy',
        'six',
        'threadpoolctl',
        'typing_extensions',
        'tzdata',
        'wrapt',
        'XlsxWriter',
        'zipp',
    ],
    classifiers=[
        'Programming Language :: Python :: 3',
        'License :: OSI Approved :: MIT License',
        'Operating System :: OS Independent',
    ],
    python_requires='>=3.7',
)
