
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-06-04T12:52:09-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "c3674a0bb04afada69199ee7863cae83ef6a89ef",
 "version": "2.9.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
