# This file was auto-generated by Fern from our API Definition.

import enum
import typing

T_Result = typing.TypeVar("T_Result")


class CredentialField(str, enum.Enum):
    """
    Enum of all available values.
    """

    KIND_NAME = "KIND_NAME"
    ID = "ID"
    REVISION = "REVISION"
    CREATED_AT = "CREATED_AT"
    MODIFIED_AT = "MODIFIED_AT"
    ETAG = "ETAG"
    DATA_HAS_PROOF = "DATA_HAS_PROOF"
    DATA_HOLDER = "DATA_HOLDER"
    DATA_ID = "DATA_ID"
    DATA_ISSUER = "DATA_ISSUER"
    DATA_VALID_FROM = "DATA_VALID_FROM"
    DATA_VALID_UNTIL = "DATA_VALID_UNTIL"
    DELETED_AT = "DELETED_AT"

    def visit(
        self,
        kind_name: typing.Callable[[], T_Result],
        id: typing.Callable[[], T_Result],
        revision: typing.Callable[[], T_Result],
        created_at: typing.Callable[[], T_Result],
        modified_at: typing.Callable[[], T_Result],
        etag: typing.Callable[[], T_Result],
        data_has_proof: typing.Callable[[], T_Result],
        data_holder: typing.Callable[[], T_Result],
        data_id: typing.Callable[[], T_Result],
        data_issuer: typing.Callable[[], T_Result],
        data_valid_from: typing.Callable[[], T_Result],
        data_valid_until: typing.Callable[[], T_Result],
        deleted_at: typing.Callable[[], T_Result],
    ) -> T_Result:
        if self is CredentialField.KIND_NAME:
            return kind_name()
        if self is CredentialField.ID:
            return id()
        if self is CredentialField.REVISION:
            return revision()
        if self is CredentialField.CREATED_AT:
            return created_at()
        if self is CredentialField.MODIFIED_AT:
            return modified_at()
        if self is CredentialField.ETAG:
            return etag()
        if self is CredentialField.DATA_HAS_PROOF:
            return data_has_proof()
        if self is CredentialField.DATA_HOLDER:
            return data_holder()
        if self is CredentialField.DATA_ID:
            return data_id()
        if self is CredentialField.DATA_ISSUER:
            return data_issuer()
        if self is CredentialField.DATA_VALID_FROM:
            return data_valid_from()
        if self is CredentialField.DATA_VALID_UNTIL:
            return data_valid_until()
        if self is CredentialField.DELETED_AT:
            return deleted_at()
