# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

from .credential_11 import Credential11


class DataModelCredential_Vc11(Credential11):
    datamodel: typing.Literal["vc1_1"]

    class Config:
        frozen = True
        smart_union = True
        allow_population_by_field_name = True


DataModelCredential = typing.Union[DataModelCredential_Vc11]
