# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

from .filter_timestamp_between import FilterTimestampBetween
from .filter_timestamp_equal import FilterTimestampEqual
from .filter_timestamp_greater_than import FilterTimestampGreaterThan
from .filter_timestamp_greater_than_or_equal import FilterTimestampGreaterThanOrEqual
from .filter_timestamp_less_than import FilterTimestampLessThan
from .filter_timestamp_less_than_or_equal import FilterTimestampLessThanOrEqual
from .filter_timestamp_not_equal import FilterTimestampNotEqual


class FilterTimestamp_Between(FilterTimestampBetween):
    operator: typing.Literal["BETWEEN"]

    class Config:
        frozen = True
        smart_union = True
        allow_population_by_field_name = True


class FilterTimestamp_Equal(FilterTimestampEqual):
    operator: typing.Literal["EQUAL"]

    class Config:
        frozen = True
        smart_union = True
        allow_population_by_field_name = True


class FilterTimestamp_GreaterThan(FilterTimestampGreaterThan):
    operator: typing.Literal["GREATER_THAN"]

    class Config:
        frozen = True
        smart_union = True
        allow_population_by_field_name = True


class FilterTimestamp_GreaterThanOrEqual(FilterTimestampGreaterThanOrEqual):
    operator: typing.Literal["GREATER_THAN_OR_EQUAL"]

    class Config:
        frozen = True
        smart_union = True
        allow_population_by_field_name = True


class FilterTimestamp_LessThan(FilterTimestampLessThan):
    operator: typing.Literal["LESS_THAN"]

    class Config:
        frozen = True
        smart_union = True
        allow_population_by_field_name = True


class FilterTimestamp_LessThanOrEqual(FilterTimestampLessThanOrEqual):
    operator: typing.Literal["LESS_THAN_OR_EQUAL"]

    class Config:
        frozen = True
        smart_union = True
        allow_population_by_field_name = True


class FilterTimestamp_NotEqual(FilterTimestampNotEqual):
    operator: typing.Literal["NOT_EQUAL"]

    class Config:
        frozen = True
        smart_union = True
        allow_population_by_field_name = True


FilterTimestamp = typing.Union[
    FilterTimestamp_Between,
    FilterTimestamp_Equal,
    FilterTimestamp_GreaterThan,
    FilterTimestamp_GreaterThanOrEqual,
    FilterTimestamp_LessThan,
    FilterTimestamp_LessThanOrEqual,
    FilterTimestamp_NotEqual,
]
