# This file was auto-generated by Fern from our API Definition.

import enum
import typing

T_Result = typing.TypeVar("T_Result")


class SortOrder(str, enum.Enum):
    """
    Enum of all possible sort order values.
    """

    ASC = "ASC"
    DESC = "DESC"

    def visit(self, asc: typing.Callable[[], T_Result], desc: typing.Callable[[], T_Result]) -> T_Result:
        if self is SortOrder.ASC:
            return asc()
        if self is SortOrder.DESC:
            return desc()
