# Generated by Django 4.1.6 on 2023-07-06 15:01

from django.db import migrations, models
import django_ticketbai.validators


class Migration(migrations.Migration):

    dependencies = [
        ("django_ticketbai", "0004_invoice_csv_code_invoice_tbai_code_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Config",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prefix", models.CharField(max_length=5)),
                ("suffix", models.CharField(blank=True, max_length=5, null=True)),
                (
                    "pks12",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="certs",
                        validators=[django_ticketbai.validators.validate_pks_extension],
                        verbose_name="Certificate",
                    ),
                ),
                ("password", models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                "verbose_name": "Configuration",
                "verbose_name_plural": "Configurations",
            },
        ),
        migrations.AlterField(
            model_name="invoice",
            name="simplified",
            field=models.CharField(default="N", max_length=2),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="vat_regime",
            field=models.CharField(default="01", max_length=2),
        ),
    ]
