# Generated by Django 4.1.6 on 2023-07-28 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("django_ticketbai", "0011_alter_invoice_signature_value"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="pre_invoice",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="django_ticketbai.invoice",
                verbose_name="Previous invoice",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="signature_value",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Sinadura balioa"
            ),
        ),
    ]
