import platform as _platform

PLATFORM = _platform.system()
MODIFIERS = ['Shift', 'Alt', 'Control']
KEY_MAPPING = {
    'Escape': ['Qt.Key_Escape', 27],
    'Enter': ['Qt.Key_Return', 13],
    'Space': ['Qt.Key_Space', 32],
    'Backspace': ['Qt.Key_Backspace', 8],
    'Tab': ['Qt.Key_Tab', 9],
    'Shift': ['Qt.ShiftModifier', [304, 303]],  # left and right shift
    'Control': ['Qt.ControlModifier', [306, 305]],  # left and right control
    'Alt': ['Qt.AltModifier', [308, 307]],  # left and right alt
    'Left Arrow': ['Qt.Key_Left', 276],
    'Up Arrow': ['Qt.Key_Up', 273],
    'Right Arrow': ['Qt.Key_Right', 275],
    'Down Arrow': ['Qt.Key_Down', 274],
    'A': ['Qt.Key_A', 97],
    'B': ['Qt.Key_B', 98],
    'C': ['Qt.Key_C', 99],
    'D': ['Qt.Key_D', 100],
    'E': ['Qt.Key_E', 101],
    'F': ['Qt.Key_F', 102],
    'G': ['Qt.Key_G', 103],
    'H': ['Qt.Key_H', 104],
    'I': ['Qt.Key_I', 105],
    'J': ['Qt.Key_J', 106],
    'K': ['Qt.Key_K', 107],
    'L': ['Qt.Key_L', 108],
    'M': ['Qt.Key_M', 109],
    'N': ['Qt.Key_N', 110],
    'O': ['Qt.Key_O', 111],
    'P': ['Qt.Key_P', 112],
    'Q': ['Qt.Key_Q', 113],
    'R': ['Qt.Key_R', 114],
    'S': ['Qt.Key_S', 115],
    'T': ['Qt.Key_T', 116],
    'U': ['Qt.Key_U', 117],
    'V': ['Qt.Key_V', 118],
    'W': ['Qt.Key_W', 119],
    'X': ['Qt.Key_X', 120],
    'Y': ['Qt.Key_Y', 121],
    'Z': ['Qt.Key_Z', 122],
    '0': ['Qt.Key_0', 48],
    '1': ['Qt.Key_1', 49],
    '2': ['Qt.Key_2', 50],
    '3': ['Qt.Key_3', 51],
    '4': ['Qt.Key_4', 52],
    '5': ['Qt.Key_5', 53],
    '6': ['Qt.Key_6', 54],
    '7': ['Qt.Key_7', 55],
    '8': ['Qt.Key_8', 56],
    '9': ['Qt.Key_9', 57],
}
