queries = [
    "Find case studies services:'Digital Maturity' by ps or rzf",
    "McDonald",
    "'Nissan'",
    "client_name:'Delta' services:'Digital Maturity'",
    "client_name:'Delta'",
    "find case studies about Delta airlines",
    "capabilities:'Digital Business Transformation'",
    "file_name:'Chevron_Business Transformation Strategy MC Learning_Case Study_2019' client_name:Chevron",
    "file_name:'Chevron_Business Transformation Strategy MC Learning_Case Study_2019.pdf' client_name:Chevron",
    "file_name:Chevron_Business",
    "client_name:McDonald's",
    "client_name:Chevron",
    "Find case studies -'open-source'",
    "Find examples of a digital maturity model and how to define one",
    "Find examples of a 'digital maturity model' and how to define one",
    "Find examples of leveraging 'microservices' for speed",
    "Find examples of a martech engagement in North America",
    "Find examples of building a first party data approach",
    "Find example of successful digital business transformation projects in North America",
    "Find examples of omni channel strategy & implementation work",
    "Find case studies for shifting a clients operating model in the United States",
    "Find examples of work for automotive clients in the United States from no later than 2022",
    "Find case studies in the beauty industry where we have used Salesforce technologies",
    "Find case studies for customer experience work in the retail space in asia between 2016 & 18",
    "Find case studies for customer experience work in the retail or telecom space in asia or europe between 2016 & 24",
    "Find examples of work for beauty clients in the United States or Brazil between 2019 and 2021",
    "Find examples in financial services in europe before 2023",
    "Find examples in financial services or retail in europe or NA before 2023 but after 2021 delivered by publicis sapient",
    "Find examples in financial services or retail in europe or NA before 2023 but after 2021 delivered by any ps or digitas",
    "Find examples in financial services or retail in north america before 2023 but after 2020 delivered by ps or rzf",
    "Find examples in financial services or retail in north america before 2023 but after 2020 delivered by ps",
    "Find case studies for banks in Southeast Asia only from 2022 or later.",
    "Find example of successful digital business transformation projects in North America between 2022 & 2023 in the health industry.",
    "Find case studies for shifting a clients operating model in automotive, between 2020 and 2021.",
    "Find me case studies similar to the work we did at Lloyds",
    "Find examples of a marketing data strategy which includes the deployment of a mesh CDP in the first quarter of the project.",
    "Find an example of an A/B testing tool evaluation where Optimizely was a clear winner.",
    "Find examples of data platform that included data visualization, segmentation and a test and learn program.",
    "Find examples of timelines for implementing CDP use cases.",
    "Find examples of customer segmentation programs that use audio, social and email.",
    "Find examples of how to implement Optimizely full stack",
    "Find examples where we leveraged Epsilon data in the healthcare space, specifically to build personalized marketing experiences.",
    "Find examples of a customer dashboard that includes geography, device and social engagement.",
    "Find me examples where we implemented machine learning to address churn.",
    "Find examples of a healthcare client where we built a personalized marketing stack, before 2019.",
    "Find examples where we have leveraged 'Oracle & SAP' as data sources for business insights after 2023",
    "Find examples of steps taken to deliver 'investment planning operating model' before 2022",
    "What projected sales impact have we seen when delivering 'personalization at scale' between 2020 and 2024?",
    "Find examples of 'marketing transformation' business cases in 2023.",
    "Find examples of an agile marketing operating model, and the key pillars within it in the last three years.",
    "Find examples of an agile marketing pod and their structure in the last 24 months.",
    "Find examples of an Digital Strategy Model by any ps or rzf agency in the past year.",
    "Provide an example of how you have successfully worked cross-functionally across your network for a global client. Any systems you have in place to ensure seamless operations should be highlighted. Ideal example would include collaboration across different regional solutions.",
    "Provide a mini case demonstrating Point of Care Channel Experience success and highlights of your capabilities.",
    "Social is a key channel for BMS. Provide a mini case showing your expertise and summarize your capabilities.",
    "Can you please provide a case study that showcases how you’ve successfully executed an Omnichannel campaign? (Right content to the right person in the right channel at the right cadence) - How was success of this case study measured? - Please showcase the evolution in your thinking and approach – crawl, walk, run, fly - Please show how this thinking could be applied to a broader PCP and DTC launch - how did measurement influence the strategy?",
    "Create a case study showcasing your agency’s role in driving and developing the experience across audiences, as well as your approach/thinking",
    "Please provide a case study that shows how your agency has created and executed a successful omni-channel marketing campaign, ideally driving alignment of messages/timing across tactics, immediate feedback loops, and considerations of messages/tactics across stakeholders (e.g. Consumers and HCPs)",
    "Provide an example of how you helped a client approach innovation with data driven rationale, utilizing approaches that were not new to the marketplace but new to that client.",
    "Please share a case study that covers this topic. It is recommended that the case study provides the following: • Relevance to the Selection Criteria, • If and how any partner agencies were involved, • Challenge • Strategic thinking the agency brought to the client • Solution • Results • Year the case was completed",
    "How does your agency maximize the use of data for media planning and buying? Please detail how you execute data-driven audience-led planning, as well as the creative and technological needs that supported it.",
    "What does a “good” measurement framework look like? Please share a case study of how you have evolved a client’s measurement framework when working together, including the requirements from both sides, the timeline, and outcomes.",
    "Provide a detailed case example where real-time measurement and speedy campaign/media optimizations were performed to drive increased effectiveness and efficiencies for a large consumer media campaign",
    "Explain how you partnered with the client’s marketing and internal analytics teams, as well as other agency partners, to develop a holistic view of brand performance",
    "How do you collaborate with other clients in establishing and optimizing multiple KPIs?",
    "Crowded competitive landscape launch case study leveraging client-developed systems and infrastructure",
    "create a case study that Demonstrates an understanding of the unique nature of launch campaigns in a competitive therapeutic area",
    "Create a case study showcasing a co-promote launch if available",
    "Share Experience working across co-promote/collaboration products between two pharmaceutical manufacturers supporting one brand",
    "Create a relevant case for a major brand launch. In the cases, provide the situation, timing, your contribution, and any results you are permitted to share.",
    "Create a case study showcasing an accelerated approval scenario if available",
    "Relevant case for a small spending brand with a small target audience In the cases, provide the situation, timing, your contribution, and any results you are permitted to share.",
    "Share your Expertise with Rx products that treat rare disease",
    "Navigating the value chain so that DTC media programs result in driving patients to ask for the Rx from their doctor is a priority for BMS. Please share a mini case on how you have accomplished this before for another DTC brand",
    "Share example(s) of best-in-class media strategy and tactics from the brand / initiative media strategies for rare disease",
    "Share how you have applied an innovative staffing solution to a heavily matrixed organization, with strong leadership to ensure the right relationships are established across client/agency teams to support a complex account with agility in the day-to-day business.",
    "How has your agency developed processes and worked collaboratively with the internal marketing teams at a highly matrixed organization that have either multiple lines of business or distinct therapeutic areas?",
    "You are the keeper of all the Case Studies within Lionbox, and are tasked with finding the best case study for use in an RFP. Using the key words Case Study or Example in the file contacts of PowerPoint documents only, find every case study that mentions the word launch in the last 24 months. If the case study has a mention of the word DSA in the case study as well, separate that out in a different list and provide the two to three sentences surrounding the mention so it can be checked. Once we have found all the case studies, reformat any that you would consider presentation-ready to have a more written format with word counts around 100 words for each section.",
    "Using your knowledge of all the folders in the BD folder, please help me determine all the times we used the case study titled 'Understanding physicians as people through CareStyles to unveil shifts in media prioritizations' and share the links to the final files were these case studies appear within Box.",
    "We need some talking points on our CRM work for Marriott Bonvoy for the GM pitch",
    "Customer Data Strategy – Anything from RZF, PS is giving their input I would also like to show up if it makes sense.",
    "Digital Customer Experience – Slides on how we approach this work and best in class examples",
    "Personalization Strategy – Content creation, Journey Orchestration, DCO",
    "Have you come across any folders with B2B FinServ/Bank cases from Digitas or RZF?",
    "Can you help me pull some PO1 content? Looking for written summaries of our relationships with Samsung and Stellantis.",
    "2 case studies of enterprise loyalty strategy design projects",
    "What proprietary insights and research tools do you bring to these engagements?",
    "How do you support different industries?",
    "1 example each of enterprise strategy and loyalty program business cases.",
    "Case study for customer engagement strategy design and execution project.",
    "What tools and techniques do you incorporate to improve CX and engagement?",
    "Present 2 client case studies on how you improved or optimized emotional loyalty.",
    "1 case study of a program design engagement where both financial and experiential rewards were incorporated",
    "Please walk us through two case studies of campaign and offer design projects, including the following:        Targeting methodology        Touchpoints reached (with special focus on social media)        Examples of any content and/or creative developed        Any changes made mid-campaign for optimization     How the anticipated costs and results were presented to the client",
    "I am looking for a PDX slide that shows our agency brands/PO1s as the PDX pillar within Groupe. Something that makes it clear what is in PDX.",
    "Is there a Groupe level FS creds slide- especially key clients?",
    "Walk us through an example of your typical program design process.",
    "In your experience what is the best way to collaborate with other ALDI agency partners? Specifically, please provide your experience of working with retail companies and how you will implement those learnings for ALDI’s benefit.",
    "How do you develop a clear understanding of the market and the target consumer?",
    "What methods, tools, systems, research, and data do you deploy to generate insight and validate media selection?",
    "How do you determine what the best channel combinations are and what they contribute?",
    "How do you make inter-media selections e.g., use of partnerships, cross-channel, cross-platform decisions?",
    "What steps do you take to determine ideal communication levels e.g., coverage and frequency distribution targets, flighting, quality parameters, appropriate advertising environments, etc. (and how would you help to define use of creative assets accordingly)? ",
    "What would your recommendation be in response to important regulatory issues, and how they might impact ALDI media planning (e.g., HFSS, deprecation of third-party cookie, etc)",
    "Please illustrate the process you have in place and follow, and the systems you use, for the purposes of implementational planning and buying, including:  The craft skills necessary to execute the plan as approved.",
    "How will you deliver a disclosed media buying approach to ensure full transparency for ALDI including providing a clear understanding /articulation of media budget allocation and vendor selection?",
    "What reporting discipline will be adopted to ensure the client is informed / involved as appropriate?",
    "In the absence of 1st party data, how would you identify and activate relevant audience insights?",
    "Ad fraud, viewability and brand safety: please outline your process for ensuring ad fraud, viewability and brand safety risks are mitigated, addressed and tracked in each digital channel. Please list all details including internal and external tools, methods for ‘make goods’, inclusion/exclusion lists, standards applied, frequency of review and updates.",
    "We require a Marketing Network Partner who can manage 50+ global and regional charters (plus other local projects) per annum; how will you scale-up to deliver work effectively? Please provide evidence where this is also being done for other similar clients",
    "What can we achieve together when we integrate Creativity, Media, Data and Technology? Please demonstrate through live client examples (similar scale & complexity as TCCC), specific use cases where this integrated model has delivered incremental effectiveness and efficiency benefits?",
    "Where have you established and managed CICs for other global brands with similar scale and complexity? Note: TCCC currently has 22 CICs covering most markets and languages. Please share 1 success story related to recruiting through 'owned handles', building communities of consumer supporters through real-time reactions, real-time consent & conversations (immediate & planned). Please share an example where this approach was less effective and your learnings",
    "What capabilities and technologies do you have to operationalize TCCC's vision for eCommerce as described in the brief? Do you have prior expertise in supporting other global CPGs / brands in ther eCommerce ambitions? Please provide case studies / examples and highlight the business impact you had.",
    "I am looking for a PDX slide that shows our agency brands/PO1s as the PDX pillar within Groupe. Something that makes it clear what is in PDX. Is there a Groupe level FS creds slide- especially key clients?",
    "Walk us through an example of your typical program design process.",
    "Can you show me examples of successful marketing campaigns we've run in retail or CPG?",
    "What strategies does Pub Media use to improve engagement on social media?",
    "How do we measure the effectiveness of digital marketing campaigns?",
    "What innovations in data analytics have we implemented recently?",
    "Where have we demonstrated our approach to content marketing in a competitive market?",
    "Illustrate how you have built an agile, flexible bespoke HoCo/full funnel model to support a client across multiple brands, segments, and geographies. What were the challenges & benefits experienced for both the client and your company? What are the lessons learned for the Accor business?",
    "Illustrate how you have supported and helped enable a client's governance process to ensure alignment and accountability. How did you ensure affordability and commercial optimisation for the client?",
    "How did you ensure appropriate focus and commitment to all brands and regions – ensuring satisfaction as a valued partner across the client teams and stakeholders?",
    "Illustrate your approach to targeting and segmentation to ensure appropriate focus / avoid cannibalisation across a diverse portfolio of brands.",
    "Show how you have brought multi-market/regional audience insight to bear on global strategy and utilised data to enable more relevant experiences and conversion in local markets while maintaining brand consistency globally.",
]
