
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-06-05T14:08:55-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "a9c872f596bd5b89f7f8bd717830a3fcd380d36a",
 "version": "2024.6.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
