import os

IS_ON_PREM = os.getenv("IS_ON_PREM", "false")
FALLBACK_HARDCODED_DATA_KEY = "WyxHYW0kZSomMGBzTn1+Y1RRUT8vYTY="
ON_PREM_DATA_KEY = os.getenv("ON_PREM_DATA_KEY", FALLBACK_HARDCODED_DATA_KEY)
