# coding: utf-8

"""
    GroupDocs.Rewriter API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 24.4.0
    Contact: anton.perhunov@aspose.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class TrialSupportedFormats(str, Enum):
    """
    TrialSupportedFormats
    """

    """
    allowed enum values
    """
    DOCX = 'Docx'
    PDF = 'Pdf'

    @classmethod
    def from_json(cls, json_str: str) -> TrialSupportedFormats:
        """Create an instance of TrialSupportedFormats from a JSON string"""
        return TrialSupportedFormats(json.loads(json_str))


