
#===========================================================
#            Copyright (C) 2023-present AyiinXd
#===========================================================
#||                                                       ||
#||              _         _ _      __  __   _            ||
#||             /   _   _(_|_)_ __  / /__| |           ||
#||            / _ | | | | | | '_     _  | |           ||
#||           / ___  |_| | | | | | |/   (_| |           ||
#||          /_/   ___, |_|_|_| |_/_/___,_|           ||
#||                  |___/                                ||
#||                                                       ||
#===========================================================
# Appreciating the work of others is not detrimental to you
#===========================================================
#

from .inputPeer import InputPeer
from .inputUser import InputUser
from .inputContact import InputContact
from .inputFile import InputFile
from .inputMedia import InputMedia
from .inputChatPhoto import InputChatPhoto
from .inputGeoPoint import InputGeoPoint
from .inputPhoto import InputPhoto
from .inputFileLocation import InputFileLocation
from .peer import Peer
from .rpcResult import RpcResult
from .rpcError import RpcError
from .rpcDropAnswer import RpcDropAnswer
from .user import User
from .userProfilePhoto import UserProfilePhoto
from .userStatus import UserStatus
from .chat import Chat
from .chatFull import ChatFull
from .chatParticipant import ChatParticipant
from .chatParticipants import ChatParticipants
from .chatPhoto import ChatPhoto
from .message import Message
from .messageMedia import MessageMedia
from .messageAction import MessageAction
from .dialog import Dialog
from .photo import Photo
from .photoSize import PhotoSize
from .geoPoint import GeoPoint
from .inputNotifyPeer import InputNotifyPeer
from .inputPeerNotifySettings import InputPeerNotifySettings
from .peerNotifySettings import PeerNotifySettings
from .peerSettings import PeerSettings
from .wallPaper import WallPaper
from .userFull import UserFull
from .contact import Contact
from .importedContact import ImportedContact
from .contactStatus import ContactStatus
from .messagesFilter import MessagesFilter
from .update import Update
from .updates import Updates
from .dcOption import DcOption
from .config import Config
from .nearestDc import NearestDc
from .encryptedChat import EncryptedChat
from .inputEncryptedChat import InputEncryptedChat
from .encryptedFile import EncryptedFile
from .inputEncryptedFile import InputEncryptedFile
from .encryptedMessage import EncryptedMessage
from .inputDocument import InputDocument
from .document import Document
from .notifyPeer import NotifyPeer
from .sendMessageAction import SendMessageAction
from .inputPrivacyRule import InputPrivacyRule
from .privacyRule import PrivacyRule
from .accountDaysTTL import AccountDaysTTL
from .documentAttribute import DocumentAttribute
from .stickerPack import StickerPack
from .webPage import WebPage
from .authorization import Authorization
from .receivedNotifyMessage import ReceivedNotifyMessage
from .exportedChatInvite import ExportedChatInvite
from .chatInvite import ChatInvite
from .inputStickerSet import InputStickerSet
from .stickerSet import StickerSet
from .botCommand import BotCommand
from .botInfo import BotInfo
from .keyboardButton import KeyboardButton
from .keyboardButtonRow import KeyboardButtonRow
from .replyMarkup import ReplyMarkup
from .messageEntity import MessageEntity
from .inputChannel import InputChannel
from .messageRange import MessageRange
from .channelMessagesFilter import ChannelMessagesFilter
from .channelParticipant import ChannelParticipant
from .channelParticipantsFilter import ChannelParticipantsFilter
from .inputBotInlineMessage import InputBotInlineMessage
from .inputBotInlineResult import InputBotInlineResult
from .botInlineMessage import BotInlineMessage
from .botInlineResult import BotInlineResult
from .exportedMessageLink import ExportedMessageLink
from .messageFwdHeader import MessageFwdHeader
from .inputBotInlineMessageID import InputBotInlineMessageID
from .inlineBotSwitchPM import InlineBotSwitchPM
from .topPeer import TopPeer
from .topPeerCategoryPeers import TopPeerCategoryPeers
from .draftMessage import DraftMessage
from .stickerSetCovered import StickerSetCovered
from .maskCoords import MaskCoords
from .inputStickeredMedia import InputStickeredMedia
from .game import Game
from .inputGame import InputGame
from .highScore import HighScore
from .richText import RichText
from .pageBlock import PageBlock
from .dataJSON import DataJSON
from .labeledPrice import LabeledPrice
from .invoice import Invoice
from .paymentCharge import PaymentCharge
from .postAddress import PostAddress
from .paymentRequestedInfo import PaymentRequestedInfo
from .paymentSavedCredentials import PaymentSavedCredentials
from .webDocument import WebDocument
from .inputWebDocument import InputWebDocument
from .inputWebFileLocation import InputWebFileLocation
from .inputPaymentCredentials import InputPaymentCredentials
from .shippingOption import ShippingOption
from .inputStickerSetItem import InputStickerSetItem
from .inputPhoneCall import InputPhoneCall
from .phoneCall import PhoneCall
from .phoneConnection import PhoneConnection
from .phoneCallProtocol import PhoneCallProtocol
from .cdnPublicKey import CdnPublicKey
from .cdnConfig import CdnConfig
from .langPackString import LangPackString
from .langPackDifference import LangPackDifference
from .langPackLanguage import LangPackLanguage
from .channelAdminLogEventAction import ChannelAdminLogEventAction
from .channelAdminLogEvent import ChannelAdminLogEvent
from .channelAdminLogEventsFilter import ChannelAdminLogEventsFilter
from .popularContact import PopularContact
from .recentMeUrl import RecentMeUrl
from .inputSingleMedia import InputSingleMedia
from .webAuthorization import WebAuthorization
from .inputMessage import InputMessage
from .inputDialogPeer import InputDialogPeer
from .dialogPeer import DialogPeer
from .fileHash import FileHash
from .inputClientProxy import InputClientProxy
from .inputSecureFile import InputSecureFile
from .secureFile import SecureFile
from .secureData import SecureData
from .securePlainData import SecurePlainData
from .secureValue import SecureValue
from .inputSecureValue import InputSecureValue
from .secureValueHash import SecureValueHash
from .secureValueError import SecureValueError
from .secureCredentialsEncrypted import SecureCredentialsEncrypted
from .savedContact import SavedContact
from .passwordKdfAlgo import PasswordKdfAlgo
from .securePasswordKdfAlgo import SecurePasswordKdfAlgo
from .secureSecretSettings import SecureSecretSettings
from .inputCheckPasswordSRP import InputCheckPasswordSRP
from .secureRequiredType import SecureRequiredType
from .inputAppEvent import InputAppEvent
from .jSONObjectValue import JSONObjectValue
from .jSONValue import JSONValue
from .pageTableCell import PageTableCell
from .pageTableRow import PageTableRow
from .pageCaption import PageCaption
from .pageListItem import PageListItem
from .pageListOrderedItem import PageListOrderedItem
from .pageRelatedArticle import PageRelatedArticle
from .page import Page
from .pollAnswer import PollAnswer
from .poll import Poll
from .pollAnswerVoters import PollAnswerVoters
from .pollResults import PollResults
from .chatOnlines import ChatOnlines
from .statsURL import StatsURL
from .chatAdminRights import ChatAdminRights
from .chatBannedRights import ChatBannedRights
from .inputWallPaper import InputWallPaper
from .codeSettings import CodeSettings
from .wallPaperSettings import WallPaperSettings
from .autoDownloadSettings import AutoDownloadSettings
from .emojiKeyword import EmojiKeyword
from .emojiKeywordsDifference import EmojiKeywordsDifference
from .emojiURL import EmojiURL
from .emojiLanguage import EmojiLanguage
from .folder import Folder
from .inputFolderPeer import InputFolderPeer
from .folderPeer import FolderPeer
from .urlAuthResult import UrlAuthResult
from .channelLocation import ChannelLocation
from .peerLocated import PeerLocated
from .restrictionReason import RestrictionReason
from .inputTheme import InputTheme
from .theme import Theme
from .inputThemeSettings import InputThemeSettings
from .themeSettings import ThemeSettings
from .webPageAttribute import WebPageAttribute
from .bankCardOpenUrl import BankCardOpenUrl
from .dialogFilter import DialogFilter
from .dialogFilterSuggested import DialogFilterSuggested
from .statsDateRangeDays import StatsDateRangeDays
from .statsAbsValueAndPrev import StatsAbsValueAndPrev
from .statsPercentValue import StatsPercentValue
from .statsGraph import StatsGraph
from .videoSize import VideoSize
from .statsGroupTopPoster import StatsGroupTopPoster
from .statsGroupTopAdmin import StatsGroupTopAdmin
from .statsGroupTopInviter import StatsGroupTopInviter
from .globalPrivacySettings import GlobalPrivacySettings
from .messageViews import MessageViews
from .messageReplyHeader import MessageReplyHeader
from .messageReplies import MessageReplies
from .peerBlocked import PeerBlocked
from .groupCall import GroupCall
from .inputGroupCall import InputGroupCall
from .groupCallParticipant import GroupCallParticipant
from .chatInviteImporter import ChatInviteImporter
from .chatAdminWithInvites import ChatAdminWithInvites
from .groupCallParticipantVideoSourceGroup import GroupCallParticipantVideoSourceGroup
from .groupCallParticipantVideo import GroupCallParticipantVideo
from .botCommandScope import BotCommandScope
from .sponsoredMessage import SponsoredMessage
from .searchResultsCalendarPeriod import SearchResultsCalendarPeriod
from .searchResultsPosition import SearchResultsPosition
from .reactionCount import ReactionCount
from .messageReactions import MessageReactions
from .availableReaction import AvailableReaction
from .messagePeerReaction import MessagePeerReaction
from .groupCallStreamChannel import GroupCallStreamChannel
from .attachMenuBotIconColor import AttachMenuBotIconColor
from .attachMenuBotIcon import AttachMenuBotIcon
from .attachMenuBot import AttachMenuBot
from .attachMenuBots import AttachMenuBots
from .attachMenuBotsBot import AttachMenuBotsBot
from .webViewResult import WebViewResult
from .simpleWebViewResult import SimpleWebViewResult
from .webViewMessageSent import WebViewMessageSent
from .botMenuButton import BotMenuButton
from .notificationSound import NotificationSound
from .inputInvoice import InputInvoice
from .inputStorePaymentPurpose import InputStorePaymentPurpose
from .premiumGiftOption import PremiumGiftOption
from .paymentFormMethod import PaymentFormMethod
from .emojiStatus import EmojiStatus
from .reaction import Reaction
from .chatReactions import ChatReactions
from .emailVerifyPurpose import EmailVerifyPurpose
from .emailVerification import EmailVerification
from .premiumSubscriptionOption import PremiumSubscriptionOption
from .sendAsPeer import SendAsPeer
from .messageExtendedMedia import MessageExtendedMedia
from .stickerKeyword import StickerKeyword
from .username import Username
from .forumTopic import ForumTopic
from .defaultHistoryTTL import DefaultHistoryTTL
from .exportedContactToken import ExportedContactToken
from .requestPeerType import RequestPeerType
from .emojiList import EmojiList
from .emojiGroup import EmojiGroup
from .textWithEntities import TextWithEntities
from .autoSaveSettings import AutoSaveSettings
from .autoSaveException import AutoSaveException
from .inputBotApp import InputBotApp
from .botApp import BotApp
from .appWebViewResult import AppWebViewResult
from .inlineBotWebView import InlineBotWebView
from .readParticipantDate import ReadParticipantDate
from .inputChatlist import InputChatlist
from .exportedChatlistInvite import ExportedChatlistInvite
from .messagePeerVote import MessagePeerVote
from .storyViews import StoryViews
from .storyItem import StoryItem
from .storyView import StoryView
from .inputReplyTo import InputReplyTo
from .exportedStoryLink import ExportedStoryLink
from .storiesStealthMode import StoriesStealthMode
from .mediaAreaCoordinates import MediaAreaCoordinates
from .mediaArea import MediaArea
from .peerStories import PeerStories
from .premiumGiftCodeOption import PremiumGiftCodeOption
from .prepaidGiveaway import PrepaidGiveaway
from .boost import Boost
from .myBoost import MyBoost
from .storyFwdHeader import StoryFwdHeader
from .postInteractionCounters import PostInteractionCounters
from .publicForward import PublicForward
from .peerColor import PeerColor
from .storyReaction import StoryReaction
from .savedDialog import SavedDialog
from .savedReactionTag import SavedReactionTag
from .outboxReadDate import OutboxReadDate
from .smsJob import SmsJob
from .businessWeeklyOpen import BusinessWeeklyOpen
from .businessWorkHours import BusinessWorkHours
from .businessLocation import BusinessLocation
from .inputBusinessRecipients import InputBusinessRecipients
from .businessRecipients import BusinessRecipients
from .businessAwayMessageSchedule import BusinessAwayMessageSchedule
from .inputBusinessGreetingMessage import InputBusinessGreetingMessage
from .businessGreetingMessage import BusinessGreetingMessage
from .inputBusinessAwayMessage import InputBusinessAwayMessage
from .businessAwayMessage import BusinessAwayMessage
from .timezone import Timezone
from .quickReply import QuickReply
from .inputQuickReplyShortcut import InputQuickReplyShortcut
from .connectedBot import ConnectedBot
from .birthday import Birthday
from .botBusinessConnection import BotBusinessConnection
from .inputBusinessIntro import InputBusinessIntro
from .businessIntro import BusinessIntro
from .inputCollectible import InputCollectible
from .inputBusinessBotRecipients import InputBusinessBotRecipients
from .businessBotRecipients import BusinessBotRecipients
from .contactBirthday import ContactBirthday
from .missingInvitee import MissingInvitee
from .inputBusinessChatLink import InputBusinessChatLink
from .businessChatLink import BusinessChatLink
from .requestedPeer import RequestedPeer
from .sponsoredMessageReportOption import SponsoredMessageReportOption
from .broadcastRevenueTransaction import BroadcastRevenueTransaction
from .reactionsNotifySettings import ReactionsNotifySettings
from .broadcastRevenueBalances import BroadcastRevenueBalances
from .availableEffect import AvailableEffect
from .factCheck import FactCheck
from .starsTransactionPeer import StarsTransactionPeer
from .starsTopupOption import StarsTopupOption
from .starsTransaction import StarsTransaction
