# coding: utf-8

"""
    Montelo

    Documentation for the Montelo API.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from montelo.client.openapi_client.models.subscription_dto import SubscriptionDto

class TestSubscriptionDto(unittest.TestCase):
    """SubscriptionDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SubscriptionDto:
        """Test SubscriptionDto
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SubscriptionDto`
        """
        model = SubscriptionDto()
        if include_optional:
            return SubscriptionDto(
                id = '',
                user_id = '',
                org_id = '',
                stripe_customer_id = '',
                stripe_subscription_id = '',
                details = None,
                created_at = '',
                updated_at = ''
            )
        else:
            return SubscriptionDto(
                id = '',
                stripe_customer_id = '',
                created_at = '',
                updated_at = '',
        )
        """

    def testSubscriptionDto(self):
        """Test SubscriptionDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
