# coding: utf-8

"""
    Montelo

    Documentation for the Montelo API.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from montelo.client.openapi_client.models.fine_tune_openai_input import FineTuneOpenaiInput

class TestFineTuneOpenaiInput(unittest.TestCase):
    """FineTuneOpenaiInput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FineTuneOpenaiInput:
        """Test FineTuneOpenaiInput
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FineTuneOpenaiInput`
        """
        model = FineTuneOpenaiInput()
        if include_optional:
            return FineTuneOpenaiInput(
                model = 'gpt-3.5-turbo-0125'
            )
        else:
            return FineTuneOpenaiInput(
                model = 'gpt-3.5-turbo-0125',
        )
        """

    def testFineTuneOpenaiInput(self):
        """Test FineTuneOpenaiInput"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
