# coding: utf-8

"""
    Montelo

    Documentation for the Montelo API.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from montelo.client.openapi_client.api.api_key_api import ApiKeyApi


class TestApiKeyApi(unittest.TestCase):
    """ApiKeyApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ApiKeyApi()

    def tearDown(self) -> None:
        pass

    def test_api_key_controller_get_api_keys_for_project(self) -> None:
        """Test case for api_key_controller_get_api_keys_for_project

        """
        pass

    def test_api_key_controller_reveal_one(self) -> None:
        """Test case for api_key_controller_reveal_one

        """
        pass

    def test_api_key_controller_rotate_one(self) -> None:
        """Test case for api_key_controller_rotate_one

        """
        pass


if __name__ == '__main__':
    unittest.main()
