# coding: utf-8

"""
    Montelo

    Documentation for the Montelo API.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from montelo.client.openapi_client.models.fine_tune_cohere_input import FineTuneCohereInput

class TestFineTuneCohereInput(unittest.TestCase):
    """FineTuneCohereInput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FineTuneCohereInput:
        """Test FineTuneCohereInput
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FineTuneCohereInput`
        """
        model = FineTuneCohereInput()
        if include_optional:
            return FineTuneCohereInput(
                model = 'command-r'
            )
        else:
            return FineTuneCohereInput(
                model = 'command-r',
        )
        """

    def testFineTuneCohereInput(self):
        """Test FineTuneCohereInput"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
