
#===========================================================
#            Copyright (C) 2023-present AyiinXd
#===========================================================
#||                                                       ||
#||              _         _ _      __  __   _            ||
#||             /   _   _(_|_)_ __  / /__| |           ||
#||            / _ | | | | | | '_     _  | |           ||
#||           / ___  |_| | | | | | |/   (_| |           ||
#||          /_/   ___, |_|_|_| |_/_/___,_|           ||
#||                  |___/                                ||
#||                                                       ||
#===========================================================
# Appreciating the work of others is not detrimental to you
#===========================================================
#

from .inputPeerChat import InputPeerChat
from .inputPeerUser import InputPeerUser
from .inputPeerChannel import InputPeerChannel
from .inputPeerUserFromMessage import InputPeerUserFromMessage
from .inputPeerChannelFromMessage import InputPeerChannelFromMessage
from .inputUser import InputUser
from .inputUserFromMessage import InputUserFromMessage
from .inputPhoneContact import InputPhoneContact
from .inputFile import InputFile
from .inputFileBig import InputFileBig
from .inputMediaUploadedPhoto import InputMediaUploadedPhoto
from .inputMediaPhoto import InputMediaPhoto
from .inputMediaGeoPoint import InputMediaGeoPoint
from .inputMediaContact import InputMediaContact
from .inputMediaUploadedDocument import InputMediaUploadedDocument
from .inputMediaDocument import InputMediaDocument
from .inputMediaVenue import InputMediaVenue
from .inputMediaPhotoExternal import InputMediaPhotoExternal
from .inputMediaDocumentExternal import InputMediaDocumentExternal
from .inputMediaGame import InputMediaGame
from .inputMediaInvoice import InputMediaInvoice
from .inputMediaGeoLive import InputMediaGeoLive
from .inputMediaPoll import InputMediaPoll
from .inputMediaDice import InputMediaDice
from .inputMediaStory import InputMediaStory
from .inputMediaWebPage import InputMediaWebPage
from .inputChatUploadedPhoto import InputChatUploadedPhoto
from .inputChatPhoto import InputChatPhoto
from .inputGeoPoint import InputGeoPoint
from .inputPhoto import InputPhoto
from .inputFileLocation import InputFileLocation
from .inputEncryptedFileLocation import InputEncryptedFileLocation
from .inputDocumentFileLocation import InputDocumentFileLocation
from .inputSecureFileLocation import InputSecureFileLocation
from .inputPhotoFileLocation import InputPhotoFileLocation
from .inputPhotoLegacyFileLocation import InputPhotoLegacyFileLocation
from .inputPeerPhotoFileLocation import InputPeerPhotoFileLocation
from .inputStickerSetThumb import InputStickerSetThumb
from .inputGroupCallStream import InputGroupCallStream
from .peerUser import PeerUser
from .peerChat import PeerChat
from .peerChannel import PeerChannel
from .rpcResult import RpcResult
from .rpcError import RpcError
from .rpcAnswerDropped import RpcAnswerDropped
from .userEmpty import UserEmpty
from .user import User
from .userProfilePhoto import UserProfilePhoto
from .userStatusOnline import UserStatusOnline
from .userStatusOffline import UserStatusOffline
from .userStatusRecently import UserStatusRecently
from .userStatusLastWeek import UserStatusLastWeek
from .userStatusLastMonth import UserStatusLastMonth
from .chatEmpty import ChatEmpty
from .chat import Chat
from .chatForbidden import ChatForbidden
from .channel import Channel
from .channelForbidden import ChannelForbidden
from .chatFull import ChatFull
from .channelFull import ChannelFull
from .chatParticipant import ChatParticipant
from .chatParticipantCreator import ChatParticipantCreator
from .chatParticipantAdmin import ChatParticipantAdmin
from .chatParticipantsForbidden import ChatParticipantsForbidden
from .chatParticipants import ChatParticipants
from .chatPhoto import ChatPhoto
from .messageEmpty import MessageEmpty
from .message import Message
from .messageService import MessageService
from .messageMediaPhoto import MessageMediaPhoto
from .messageMediaGeo import MessageMediaGeo
from .messageMediaContact import MessageMediaContact
from .messageMediaDocument import MessageMediaDocument
from .messageMediaWebPage import MessageMediaWebPage
from .messageMediaVenue import MessageMediaVenue
from .messageMediaGame import MessageMediaGame
from .messageMediaInvoice import MessageMediaInvoice
from .messageMediaGeoLive import MessageMediaGeoLive
from .messageMediaPoll import MessageMediaPoll
from .messageMediaDice import MessageMediaDice
from .messageMediaStory import MessageMediaStory
from .messageMediaGiveaway import MessageMediaGiveaway
from .messageMediaGiveawayResults import MessageMediaGiveawayResults
from .messageActionChatCreate import MessageActionChatCreate
from .messageActionChatEditTitle import MessageActionChatEditTitle
from .messageActionChatEditPhoto import MessageActionChatEditPhoto
from .messageActionChatAddUser import MessageActionChatAddUser
from .messageActionChatDeleteUser import MessageActionChatDeleteUser
from .messageActionChatJoinedByLink import MessageActionChatJoinedByLink
from .messageActionChannelCreate import MessageActionChannelCreate
from .messageActionChatMigrateTo import MessageActionChatMigrateTo
from .messageActionChannelMigrateFrom import MessageActionChannelMigrateFrom
from .messageActionGameScore import MessageActionGameScore
from .messageActionPaymentSentMe import MessageActionPaymentSentMe
from .messageActionPaymentSent import MessageActionPaymentSent
from .messageActionPhoneCall import MessageActionPhoneCall
from .messageActionCustomAction import MessageActionCustomAction
from .messageActionBotAllowed import MessageActionBotAllowed
from .messageActionSecureValuesSentMe import MessageActionSecureValuesSentMe
from .messageActionSecureValuesSent import MessageActionSecureValuesSent
from .messageActionGeoProximityReached import MessageActionGeoProximityReached
from .messageActionGroupCall import MessageActionGroupCall
from .messageActionInviteToGroupCall import MessageActionInviteToGroupCall
from .messageActionSetMessagesTTL import MessageActionSetMessagesTTL
from .messageActionGroupCallScheduled import MessageActionGroupCallScheduled
from .messageActionSetChatTheme import MessageActionSetChatTheme
from .messageActionWebViewDataSentMe import MessageActionWebViewDataSentMe
from .messageActionWebViewDataSent import MessageActionWebViewDataSent
from .messageActionGiftPremium import MessageActionGiftPremium
from .messageActionTopicCreate import MessageActionTopicCreate
from .messageActionTopicEdit import MessageActionTopicEdit
from .messageActionSuggestProfilePhoto import MessageActionSuggestProfilePhoto
from .messageActionRequestedPeer import MessageActionRequestedPeer
from .messageActionSetChatWallPaper import MessageActionSetChatWallPaper
from .messageActionGiftCode import MessageActionGiftCode
from .messageActionGiveawayResults import MessageActionGiveawayResults
from .messageActionBoostApply import MessageActionBoostApply
from .messageActionRequestedPeerSentMe import MessageActionRequestedPeerSentMe
from .dialog import Dialog
from .dialogFolder import DialogFolder
from .photoEmpty import PhotoEmpty
from .photo import Photo
from .photoSizeEmpty import PhotoSizeEmpty
from .photoSize import PhotoSize
from .photoCachedSize import PhotoCachedSize
from .photoStrippedSize import PhotoStrippedSize
from .photoSizeProgressive import PhotoSizeProgressive
from .photoPathSize import PhotoPathSize
from .geoPoint import GeoPoint
from .inputNotifyPeer import InputNotifyPeer
from .inputNotifyForumTopic import InputNotifyForumTopic
from .inputPeerNotifySettings import InputPeerNotifySettings
from .peerNotifySettings import PeerNotifySettings
from .peerSettings import PeerSettings
from .wallPaper import WallPaper
from .wallPaperNoFile import WallPaperNoFile
from .userFull import UserFull
from .contact import Contact
from .importedContact import ImportedContact
from .contactStatus import ContactStatus
from .inputMessagesFilterPhoneCalls import InputMessagesFilterPhoneCalls
from .updateNewMessage import UpdateNewMessage
from .updateMessageID import UpdateMessageID
from .updateDeleteMessages import UpdateDeleteMessages
from .updateUserTyping import UpdateUserTyping
from .updateChatUserTyping import UpdateChatUserTyping
from .updateChatParticipants import UpdateChatParticipants
from .updateUserStatus import UpdateUserStatus
from .updateUserName import UpdateUserName
from .updateNewAuthorization import UpdateNewAuthorization
from .updateNewEncryptedMessage import UpdateNewEncryptedMessage
from .updateEncryptedChatTyping import UpdateEncryptedChatTyping
from .updateEncryption import UpdateEncryption
from .updateEncryptedMessagesRead import UpdateEncryptedMessagesRead
from .updateChatParticipantAdd import UpdateChatParticipantAdd
from .updateChatParticipantDelete import UpdateChatParticipantDelete
from .updateDcOptions import UpdateDcOptions
from .updateNotifySettings import UpdateNotifySettings
from .updateServiceNotification import UpdateServiceNotification
from .updatePrivacy import UpdatePrivacy
from .updateUserPhone import UpdateUserPhone
from .updateReadHistoryInbox import UpdateReadHistoryInbox
from .updateReadHistoryOutbox import UpdateReadHistoryOutbox
from .updateWebPage import UpdateWebPage
from .updateReadMessagesContents import UpdateReadMessagesContents
from .updateChannelTooLong import UpdateChannelTooLong
from .updateChannel import UpdateChannel
from .updateNewChannelMessage import UpdateNewChannelMessage
from .updateReadChannelInbox import UpdateReadChannelInbox
from .updateDeleteChannelMessages import UpdateDeleteChannelMessages
from .updateChannelMessageViews import UpdateChannelMessageViews
from .updateChatParticipantAdmin import UpdateChatParticipantAdmin
from .updateNewStickerSet import UpdateNewStickerSet
from .updateStickerSetsOrder import UpdateStickerSetsOrder
from .updateStickerSets import UpdateStickerSets
from .updateBotInlineQuery import UpdateBotInlineQuery
from .updateBotInlineSend import UpdateBotInlineSend
from .updateEditChannelMessage import UpdateEditChannelMessage
from .updateBotCallbackQuery import UpdateBotCallbackQuery
from .updateEditMessage import UpdateEditMessage
from .updateInlineBotCallbackQuery import UpdateInlineBotCallbackQuery
from .updateReadChannelOutbox import UpdateReadChannelOutbox
from .updateDraftMessage import UpdateDraftMessage
from .updateChannelWebPage import UpdateChannelWebPage
from .updateDialogPinned import UpdateDialogPinned
from .updatePinnedDialogs import UpdatePinnedDialogs
from .updateBotWebhookJSON import UpdateBotWebhookJSON
from .updateBotWebhookJSONQuery import UpdateBotWebhookJSONQuery
from .updateBotShippingQuery import UpdateBotShippingQuery
from .updateBotPrecheckoutQuery import UpdateBotPrecheckoutQuery
from .updatePhoneCall import UpdatePhoneCall
from .updateLangPackTooLong import UpdateLangPackTooLong
from .updateLangPack import UpdateLangPack
from .updateChannelReadMessagesContents import UpdateChannelReadMessagesContents
from .updateChannelAvailableMessages import UpdateChannelAvailableMessages
from .updateDialogUnreadMark import UpdateDialogUnreadMark
from .updateMessagePoll import UpdateMessagePoll
from .updateChatDefaultBannedRights import UpdateChatDefaultBannedRights
from .updateFolderPeers import UpdateFolderPeers
from .updatePeerSettings import UpdatePeerSettings
from .updatePeerLocated import UpdatePeerLocated
from .updateNewScheduledMessage import UpdateNewScheduledMessage
from .updateDeleteScheduledMessages import UpdateDeleteScheduledMessages
from .updateTheme import UpdateTheme
from .updateGeoLiveViewed import UpdateGeoLiveViewed
from .updateMessagePollVote import UpdateMessagePollVote
from .updateDialogFilter import UpdateDialogFilter
from .updateDialogFilterOrder import UpdateDialogFilterOrder
from .updatePhoneCallSignalingData import UpdatePhoneCallSignalingData
from .updateChannelMessageForwards import UpdateChannelMessageForwards
from .updateReadChannelDiscussionInbox import UpdateReadChannelDiscussionInbox
from .updateReadChannelDiscussionOutbox import UpdateReadChannelDiscussionOutbox
from .updatePeerBlocked import UpdatePeerBlocked
from .updateChannelUserTyping import UpdateChannelUserTyping
from .updatePinnedMessages import UpdatePinnedMessages
from .updatePinnedChannelMessages import UpdatePinnedChannelMessages
from .updateChat import UpdateChat
from .updateGroupCallParticipants import UpdateGroupCallParticipants
from .updateGroupCall import UpdateGroupCall
from .updatePeerHistoryTTL import UpdatePeerHistoryTTL
from .updateChatParticipant import UpdateChatParticipant
from .updateChannelParticipant import UpdateChannelParticipant
from .updateBotStopped import UpdateBotStopped
from .updateGroupCallConnection import UpdateGroupCallConnection
from .updateBotCommands import UpdateBotCommands
from .updatePendingJoinRequests import UpdatePendingJoinRequests
from .updateBotChatInviteRequester import UpdateBotChatInviteRequester
from .updateMessageReactions import UpdateMessageReactions
from .updateWebViewResultSent import UpdateWebViewResultSent
from .updateBotMenuButton import UpdateBotMenuButton
from .updateTranscribedAudio import UpdateTranscribedAudio
from .updateUserEmojiStatus import UpdateUserEmojiStatus
from .updateMoveStickerSetToTop import UpdateMoveStickerSetToTop
from .updateMessageExtendedMedia import UpdateMessageExtendedMedia
from .updateChannelPinnedTopic import UpdateChannelPinnedTopic
from .updateChannelPinnedTopics import UpdateChannelPinnedTopics
from .updateUser import UpdateUser
from .updateStory import UpdateStory
from .updateReadStories import UpdateReadStories
from .updateStoryID import UpdateStoryID
from .updateStoriesStealthMode import UpdateStoriesStealthMode
from .updateSentStoryReaction import UpdateSentStoryReaction
from .updateBotChatBoost import UpdateBotChatBoost
from .updateChannelViewForumAsMessages import UpdateChannelViewForumAsMessages
from .updatePeerWallpaper import UpdatePeerWallpaper
from .updateBotMessageReaction import UpdateBotMessageReaction
from .updateBotMessageReactions import UpdateBotMessageReactions
from .updateSavedDialogPinned import UpdateSavedDialogPinned
from .updatePinnedSavedDialogs import UpdatePinnedSavedDialogs
from .updateSmsJob import UpdateSmsJob
from .updateQuickReplies import UpdateQuickReplies
from .updateNewQuickReply import UpdateNewQuickReply
from .updateDeleteQuickReply import UpdateDeleteQuickReply
from .updateQuickReplyMessage import UpdateQuickReplyMessage
from .updateDeleteQuickReplyMessages import UpdateDeleteQuickReplyMessages
from .updateBotBusinessConnect import UpdateBotBusinessConnect
from .updateBotNewBusinessMessage import UpdateBotNewBusinessMessage
from .updateBotEditBusinessMessage import UpdateBotEditBusinessMessage
from .updateBotDeleteBusinessMessage import UpdateBotDeleteBusinessMessage
from .updateNewStoryReaction import UpdateNewStoryReaction
from .updateBroadcastRevenueTransactions import UpdateBroadcastRevenueTransactions
from .updateStarsBalance import UpdateStarsBalance
from .updateShortMessage import UpdateShortMessage
from .updateShortChatMessage import UpdateShortChatMessage
from .updateShort import UpdateShort
from .updatesCombined import UpdatesCombined
from .updates import Updates
from .updateShortSentMessage import UpdateShortSentMessage
from .dcOption import DcOption
from .config import Config
from .nearestDc import NearestDc
from .encryptedChatEmpty import EncryptedChatEmpty
from .encryptedChatWaiting import EncryptedChatWaiting
from .encryptedChatRequested import EncryptedChatRequested
from .encryptedChat import EncryptedChat
from .encryptedChatDiscarded import EncryptedChatDiscarded
from .inputEncryptedChat import InputEncryptedChat
from .encryptedFile import EncryptedFile
from .inputEncryptedFileUploaded import InputEncryptedFileUploaded
from .inputEncryptedFile import InputEncryptedFile
from .inputEncryptedFileBigUploaded import InputEncryptedFileBigUploaded
from .encryptedMessage import EncryptedMessage
from .encryptedMessageService import EncryptedMessageService
from .inputDocument import InputDocument
from .documentEmpty import DocumentEmpty
from .document import Document
from .notifyPeer import NotifyPeer
from .notifyForumTopic import NotifyForumTopic
from .sendMessageUploadVideoAction import SendMessageUploadVideoAction
from .sendMessageUploadAudioAction import SendMessageUploadAudioAction
from .sendMessageUploadPhotoAction import SendMessageUploadPhotoAction
from .sendMessageUploadDocumentAction import SendMessageUploadDocumentAction
from .sendMessageUploadRoundAction import SendMessageUploadRoundAction
from .sendMessageHistoryImportAction import SendMessageHistoryImportAction
from .sendMessageEmojiInteraction import SendMessageEmojiInteraction
from .sendMessageEmojiInteractionSeen import SendMessageEmojiInteractionSeen
from .inputPrivacyValueAllowUsers import InputPrivacyValueAllowUsers
from .inputPrivacyValueDisallowUsers import InputPrivacyValueDisallowUsers
from .inputPrivacyValueAllowChatParticipants import InputPrivacyValueAllowChatParticipants
from .inputPrivacyValueDisallowChatParticipants import InputPrivacyValueDisallowChatParticipants
from .privacyValueAllowUsers import PrivacyValueAllowUsers
from .privacyValueDisallowUsers import PrivacyValueDisallowUsers
from .privacyValueAllowChatParticipants import PrivacyValueAllowChatParticipants
from .privacyValueDisallowChatParticipants import PrivacyValueDisallowChatParticipants
from .accountDaysTTL import AccountDaysTTL
from .documentAttributeImageSize import DocumentAttributeImageSize
from .documentAttributeSticker import DocumentAttributeSticker
from .documentAttributeVideo import DocumentAttributeVideo
from .documentAttributeAudio import DocumentAttributeAudio
from .documentAttributeFilename import DocumentAttributeFilename
from .documentAttributeCustomEmoji import DocumentAttributeCustomEmoji
from .stickerPack import StickerPack
from .webPageEmpty import WebPageEmpty
from .webPagePending import WebPagePending
from .webPage import WebPage
from .webPageNotModified import WebPageNotModified
from .authorization import Authorization
from .receivedNotifyMessage import ReceivedNotifyMessage
from .chatInviteExported import ChatInviteExported
from .chatInviteAlready import ChatInviteAlready
from .chatInvite import ChatInvite
from .chatInvitePeek import ChatInvitePeek
from .inputStickerSetID import InputStickerSetID
from .inputStickerSetShortName import InputStickerSetShortName
from .inputStickerSetDice import InputStickerSetDice
from .stickerSet import StickerSet
from .botCommand import BotCommand
from .botInfo import BotInfo
from .keyboardButton import KeyboardButton
from .keyboardButtonUrl import KeyboardButtonUrl
from .keyboardButtonCallback import KeyboardButtonCallback
from .keyboardButtonRequestPhone import KeyboardButtonRequestPhone
from .keyboardButtonRequestGeoLocation import KeyboardButtonRequestGeoLocation
from .keyboardButtonSwitchInline import KeyboardButtonSwitchInline
from .keyboardButtonGame import KeyboardButtonGame
from .keyboardButtonBuy import KeyboardButtonBuy
from .keyboardButtonUrlAuth import KeyboardButtonUrlAuth
from .inputKeyboardButtonUrlAuth import InputKeyboardButtonUrlAuth
from .keyboardButtonRequestPoll import KeyboardButtonRequestPoll
from .inputKeyboardButtonUserProfile import InputKeyboardButtonUserProfile
from .keyboardButtonUserProfile import KeyboardButtonUserProfile
from .keyboardButtonWebView import KeyboardButtonWebView
from .keyboardButtonSimpleWebView import KeyboardButtonSimpleWebView
from .keyboardButtonRequestPeer import KeyboardButtonRequestPeer
from .inputKeyboardButtonRequestPeer import InputKeyboardButtonRequestPeer
from .keyboardButtonRow import KeyboardButtonRow
from .replyKeyboardHide import ReplyKeyboardHide
from .replyKeyboardForceReply import ReplyKeyboardForceReply
from .replyKeyboardMarkup import ReplyKeyboardMarkup
from .replyInlineMarkup import ReplyInlineMarkup
from .messageEntityUnknown import MessageEntityUnknown
from .messageEntityMention import MessageEntityMention
from .messageEntityHashtag import MessageEntityHashtag
from .messageEntityBotCommand import MessageEntityBotCommand
from .messageEntityUrl import MessageEntityUrl
from .messageEntityEmail import MessageEntityEmail
from .messageEntityBold import MessageEntityBold
from .messageEntityItalic import MessageEntityItalic
from .messageEntityCode import MessageEntityCode
from .messageEntityPre import MessageEntityPre
from .messageEntityTextUrl import MessageEntityTextUrl
from .messageEntityMentionName import MessageEntityMentionName
from .inputMessageEntityMentionName import InputMessageEntityMentionName
from .messageEntityPhone import MessageEntityPhone
from .messageEntityCashtag import MessageEntityCashtag
from .messageEntityUnderline import MessageEntityUnderline
from .messageEntityStrike import MessageEntityStrike
from .messageEntityBankCard import MessageEntityBankCard
from .messageEntitySpoiler import MessageEntitySpoiler
from .messageEntityCustomEmoji import MessageEntityCustomEmoji
from .messageEntityBlockquote import MessageEntityBlockquote
from .inputChannel import InputChannel
from .inputChannelFromMessage import InputChannelFromMessage
from .messageRange import MessageRange
from .channelMessagesFilter import ChannelMessagesFilter
from .channelParticipant import ChannelParticipant
from .channelParticipantSelf import ChannelParticipantSelf
from .channelParticipantCreator import ChannelParticipantCreator
from .channelParticipantAdmin import ChannelParticipantAdmin
from .channelParticipantBanned import ChannelParticipantBanned
from .channelParticipantLeft import ChannelParticipantLeft
from .channelParticipantsKicked import ChannelParticipantsKicked
from .channelParticipantsBanned import ChannelParticipantsBanned
from .channelParticipantsSearch import ChannelParticipantsSearch
from .channelParticipantsContacts import ChannelParticipantsContacts
from .channelParticipantsMentions import ChannelParticipantsMentions
from .inputBotInlineMessageMediaAuto import InputBotInlineMessageMediaAuto
from .inputBotInlineMessageText import InputBotInlineMessageText
from .inputBotInlineMessageMediaGeo import InputBotInlineMessageMediaGeo
from .inputBotInlineMessageMediaVenue import InputBotInlineMessageMediaVenue
from .inputBotInlineMessageMediaContact import InputBotInlineMessageMediaContact
from .inputBotInlineMessageGame import InputBotInlineMessageGame
from .inputBotInlineMessageMediaInvoice import InputBotInlineMessageMediaInvoice
from .inputBotInlineMessageMediaWebPage import InputBotInlineMessageMediaWebPage
from .inputBotInlineResult import InputBotInlineResult
from .inputBotInlineResultPhoto import InputBotInlineResultPhoto
from .inputBotInlineResultDocument import InputBotInlineResultDocument
from .inputBotInlineResultGame import InputBotInlineResultGame
from .botInlineMessageMediaAuto import BotInlineMessageMediaAuto
from .botInlineMessageText import BotInlineMessageText
from .botInlineMessageMediaGeo import BotInlineMessageMediaGeo
from .botInlineMessageMediaVenue import BotInlineMessageMediaVenue
from .botInlineMessageMediaContact import BotInlineMessageMediaContact
from .botInlineMessageMediaInvoice import BotInlineMessageMediaInvoice
from .botInlineMessageMediaWebPage import BotInlineMessageMediaWebPage
from .botInlineResult import BotInlineResult
from .botInlineMediaResult import BotInlineMediaResult
from .exportedMessageLink import ExportedMessageLink
from .messageFwdHeader import MessageFwdHeader
from .inputBotInlineMessageID import InputBotInlineMessageID
from .inputBotInlineMessageID64 import InputBotInlineMessageID64
from .inlineBotSwitchPM import InlineBotSwitchPM
from .topPeer import TopPeer
from .topPeerCategoryPeers import TopPeerCategoryPeers
from .draftMessageEmpty import DraftMessageEmpty
from .draftMessage import DraftMessage
from .stickerSetCovered import StickerSetCovered
from .stickerSetMultiCovered import StickerSetMultiCovered
from .stickerSetFullCovered import StickerSetFullCovered
from .stickerSetNoCovered import StickerSetNoCovered
from .maskCoords import MaskCoords
from .inputStickeredMediaPhoto import InputStickeredMediaPhoto
from .inputStickeredMediaDocument import InputStickeredMediaDocument
from .game import Game
from .inputGameID import InputGameID
from .inputGameShortName import InputGameShortName
from .highScore import HighScore
from .textPlain import TextPlain
from .textBold import TextBold
from .textItalic import TextItalic
from .textUnderline import TextUnderline
from .textStrike import TextStrike
from .textFixed import TextFixed
from .textUrl import TextUrl
from .textEmail import TextEmail
from .textConcat import TextConcat
from .textSubscript import TextSubscript
from .textSuperscript import TextSuperscript
from .textMarked import TextMarked
from .textPhone import TextPhone
from .textImage import TextImage
from .textAnchor import TextAnchor
from .pageBlockTitle import PageBlockTitle
from .pageBlockSubtitle import PageBlockSubtitle
from .pageBlockAuthorDate import PageBlockAuthorDate
from .pageBlockHeader import PageBlockHeader
from .pageBlockSubheader import PageBlockSubheader
from .pageBlockParagraph import PageBlockParagraph
from .pageBlockPreformatted import PageBlockPreformatted
from .pageBlockFooter import PageBlockFooter
from .pageBlockAnchor import PageBlockAnchor
from .pageBlockList import PageBlockList
from .pageBlockBlockquote import PageBlockBlockquote
from .pageBlockPullquote import PageBlockPullquote
from .pageBlockPhoto import PageBlockPhoto
from .pageBlockVideo import PageBlockVideo
from .pageBlockCover import PageBlockCover
from .pageBlockEmbed import PageBlockEmbed
from .pageBlockEmbedPost import PageBlockEmbedPost
from .pageBlockCollage import PageBlockCollage
from .pageBlockSlideshow import PageBlockSlideshow
from .pageBlockChannel import PageBlockChannel
from .pageBlockAudio import PageBlockAudio
from .pageBlockKicker import PageBlockKicker
from .pageBlockTable import PageBlockTable
from .pageBlockOrderedList import PageBlockOrderedList
from .pageBlockDetails import PageBlockDetails
from .pageBlockRelatedArticles import PageBlockRelatedArticles
from .pageBlockMap import PageBlockMap
from .dataJSON import DataJSON
from .labeledPrice import LabeledPrice
from .invoice import Invoice
from .paymentCharge import PaymentCharge
from .postAddress import PostAddress
from .paymentRequestedInfo import PaymentRequestedInfo
from .paymentSavedCredentialsCard import PaymentSavedCredentialsCard
from .webDocument import WebDocument
from .webDocumentNoProxy import WebDocumentNoProxy
from .inputWebDocument import InputWebDocument
from .inputWebFileLocation import InputWebFileLocation
from .inputWebFileGeoPointLocation import InputWebFileGeoPointLocation
from .inputWebFileAudioAlbumThumbLocation import InputWebFileAudioAlbumThumbLocation
from .inputPaymentCredentialsSaved import InputPaymentCredentialsSaved
from .inputPaymentCredentials import InputPaymentCredentials
from .inputPaymentCredentialsApplePay import InputPaymentCredentialsApplePay
from .inputPaymentCredentialsGooglePay import InputPaymentCredentialsGooglePay
from .shippingOption import ShippingOption
from .inputStickerSetItem import InputStickerSetItem
from .inputPhoneCall import InputPhoneCall
from .phoneCallEmpty import PhoneCallEmpty
from .phoneCallWaiting import PhoneCallWaiting
from .phoneCallRequested import PhoneCallRequested
from .phoneCallAccepted import PhoneCallAccepted
from .phoneCall import PhoneCall
from .phoneCallDiscarded import PhoneCallDiscarded
from .phoneConnection import PhoneConnection
from .phoneConnectionWebrtc import PhoneConnectionWebrtc
from .phoneCallProtocol import PhoneCallProtocol
from .cdnPublicKey import CdnPublicKey
from .cdnConfig import CdnConfig
from .langPackString import LangPackString
from .langPackStringPluralized import LangPackStringPluralized
from .langPackStringDeleted import LangPackStringDeleted
from .langPackDifference import LangPackDifference
from .langPackLanguage import LangPackLanguage
from .channelAdminLogEventActionChangeTitle import ChannelAdminLogEventActionChangeTitle
from .channelAdminLogEventActionChangeAbout import ChannelAdminLogEventActionChangeAbout
from .channelAdminLogEventActionChangeUsername import ChannelAdminLogEventActionChangeUsername
from .channelAdminLogEventActionChangePhoto import ChannelAdminLogEventActionChangePhoto
from .channelAdminLogEventActionToggleInvites import ChannelAdminLogEventActionToggleInvites
from .channelAdminLogEventActionToggleSignatures import ChannelAdminLogEventActionToggleSignatures
from .channelAdminLogEventActionUpdatePinned import ChannelAdminLogEventActionUpdatePinned
from .channelAdminLogEventActionEditMessage import ChannelAdminLogEventActionEditMessage
from .channelAdminLogEventActionDeleteMessage import ChannelAdminLogEventActionDeleteMessage
from .channelAdminLogEventActionParticipantInvite import ChannelAdminLogEventActionParticipantInvite
from .channelAdminLogEventActionParticipantToggleBan import ChannelAdminLogEventActionParticipantToggleBan
from .channelAdminLogEventActionParticipantToggleAdmin import ChannelAdminLogEventActionParticipantToggleAdmin
from .channelAdminLogEventActionChangeStickerSet import ChannelAdminLogEventActionChangeStickerSet
from .channelAdminLogEventActionTogglePreHistoryHidden import ChannelAdminLogEventActionTogglePreHistoryHidden
from .channelAdminLogEventActionDefaultBannedRights import ChannelAdminLogEventActionDefaultBannedRights
from .channelAdminLogEventActionStopPoll import ChannelAdminLogEventActionStopPoll
from .channelAdminLogEventActionChangeLinkedChat import ChannelAdminLogEventActionChangeLinkedChat
from .channelAdminLogEventActionChangeLocation import ChannelAdminLogEventActionChangeLocation
from .channelAdminLogEventActionToggleSlowMode import ChannelAdminLogEventActionToggleSlowMode
from .channelAdminLogEventActionStartGroupCall import ChannelAdminLogEventActionStartGroupCall
from .channelAdminLogEventActionDiscardGroupCall import ChannelAdminLogEventActionDiscardGroupCall
from .channelAdminLogEventActionParticipantMute import ChannelAdminLogEventActionParticipantMute
from .channelAdminLogEventActionParticipantUnmute import ChannelAdminLogEventActionParticipantUnmute
from .channelAdminLogEventActionToggleGroupCallSetting import ChannelAdminLogEventActionToggleGroupCallSetting
from .channelAdminLogEventActionParticipantJoinByInvite import ChannelAdminLogEventActionParticipantJoinByInvite
from .channelAdminLogEventActionExportedInviteDelete import ChannelAdminLogEventActionExportedInviteDelete
from .channelAdminLogEventActionExportedInviteRevoke import ChannelAdminLogEventActionExportedInviteRevoke
from .channelAdminLogEventActionExportedInviteEdit import ChannelAdminLogEventActionExportedInviteEdit
from .channelAdminLogEventActionParticipantVolume import ChannelAdminLogEventActionParticipantVolume
from .channelAdminLogEventActionChangeHistoryTTL import ChannelAdminLogEventActionChangeHistoryTTL
from .channelAdminLogEventActionParticipantJoinByRequest import ChannelAdminLogEventActionParticipantJoinByRequest
from .channelAdminLogEventActionToggleNoForwards import ChannelAdminLogEventActionToggleNoForwards
from .channelAdminLogEventActionSendMessage import ChannelAdminLogEventActionSendMessage
from .channelAdminLogEventActionChangeAvailableReactions import ChannelAdminLogEventActionChangeAvailableReactions
from .channelAdminLogEventActionChangeUsernames import ChannelAdminLogEventActionChangeUsernames
from .channelAdminLogEventActionToggleForum import ChannelAdminLogEventActionToggleForum
from .channelAdminLogEventActionCreateTopic import ChannelAdminLogEventActionCreateTopic
from .channelAdminLogEventActionEditTopic import ChannelAdminLogEventActionEditTopic
from .channelAdminLogEventActionDeleteTopic import ChannelAdminLogEventActionDeleteTopic
from .channelAdminLogEventActionPinTopic import ChannelAdminLogEventActionPinTopic
from .channelAdminLogEventActionToggleAntiSpam import ChannelAdminLogEventActionToggleAntiSpam
from .channelAdminLogEventActionChangePeerColor import ChannelAdminLogEventActionChangePeerColor
from .channelAdminLogEventActionChangeProfilePeerColor import ChannelAdminLogEventActionChangeProfilePeerColor
from .channelAdminLogEventActionChangeWallpaper import ChannelAdminLogEventActionChangeWallpaper
from .channelAdminLogEventActionChangeEmojiStatus import ChannelAdminLogEventActionChangeEmojiStatus
from .channelAdminLogEventActionChangeEmojiStickerSet import ChannelAdminLogEventActionChangeEmojiStickerSet
from .channelAdminLogEvent import ChannelAdminLogEvent
from .channelAdminLogEventsFilter import ChannelAdminLogEventsFilter
from .popularContact import PopularContact
from .recentMeUrlUnknown import RecentMeUrlUnknown
from .recentMeUrlUser import RecentMeUrlUser
from .recentMeUrlChat import RecentMeUrlChat
from .recentMeUrlChatInvite import RecentMeUrlChatInvite
from .recentMeUrlStickerSet import RecentMeUrlStickerSet
from .inputSingleMedia import InputSingleMedia
from .webAuthorization import WebAuthorization
from .inputMessageID import InputMessageID
from .inputMessageReplyTo import InputMessageReplyTo
from .inputMessageCallbackQuery import InputMessageCallbackQuery
from .inputDialogPeer import InputDialogPeer
from .inputDialogPeerFolder import InputDialogPeerFolder
from .dialogPeer import DialogPeer
from .dialogPeerFolder import DialogPeerFolder
from .fileHash import FileHash
from .inputClientProxy import InputClientProxy
from .inputSecureFileUploaded import InputSecureFileUploaded
from .inputSecureFile import InputSecureFile
from .secureFile import SecureFile
from .secureData import SecureData
from .securePlainPhone import SecurePlainPhone
from .securePlainEmail import SecurePlainEmail
from .secureValue import SecureValue
from .inputSecureValue import InputSecureValue
from .secureValueHash import SecureValueHash
from .secureValueErrorData import SecureValueErrorData
from .secureValueErrorFrontSide import SecureValueErrorFrontSide
from .secureValueErrorReverseSide import SecureValueErrorReverseSide
from .secureValueErrorSelfie import SecureValueErrorSelfie
from .secureValueErrorFile import SecureValueErrorFile
from .secureValueErrorFiles import SecureValueErrorFiles
from .secureValueError import SecureValueError
from .secureValueErrorTranslationFile import SecureValueErrorTranslationFile
from .secureValueErrorTranslationFiles import SecureValueErrorTranslationFiles
from .secureCredentialsEncrypted import SecureCredentialsEncrypted
from .savedPhoneContact import SavedPhoneContact
from .passwordKdfAlgoSHA256SHA256PBKDF2HMACSHA512iter100000SHA256ModPow import PasswordKdfAlgoSHA256SHA256PBKDF2HMACSHA512iter100000SHA256ModPow
from .securePasswordKdfAlgoPBKDF2HMACSHA512iter100000 import SecurePasswordKdfAlgoPBKDF2HMACSHA512iter100000
from .securePasswordKdfAlgoSHA512 import SecurePasswordKdfAlgoSHA512
from .secureSecretSettings import SecureSecretSettings
from .inputCheckPasswordSRP import InputCheckPasswordSRP
from .secureRequiredType import SecureRequiredType
from .secureRequiredTypeOneOf import SecureRequiredTypeOneOf
from .inputAppEvent import InputAppEvent
from .jsonObjectValue import JsonObjectValue
from .jsonBool import JsonBool
from .jsonNumber import JsonNumber
from .jsonString import JsonString
from .jsonArray import JsonArray
from .jsonObject import JsonObject
from .pageTableCell import PageTableCell
from .pageTableRow import PageTableRow
from .pageCaption import PageCaption
from .pageListItemText import PageListItemText
from .pageListItemBlocks import PageListItemBlocks
from .pageListOrderedItemText import PageListOrderedItemText
from .pageListOrderedItemBlocks import PageListOrderedItemBlocks
from .pageRelatedArticle import PageRelatedArticle
from .page import Page
from .pollAnswer import PollAnswer
from .poll import Poll
from .pollAnswerVoters import PollAnswerVoters
from .pollResults import PollResults
from .chatOnlines import ChatOnlines
from .statsURL import StatsURL
from .chatAdminRights import ChatAdminRights
from .chatBannedRights import ChatBannedRights
from .inputWallPaper import InputWallPaper
from .inputWallPaperSlug import InputWallPaperSlug
from .inputWallPaperNoFile import InputWallPaperNoFile
from .codeSettings import CodeSettings
from .wallPaperSettings import WallPaperSettings
from .autoDownloadSettings import AutoDownloadSettings
from .emojiKeyword import EmojiKeyword
from .emojiKeywordDeleted import EmojiKeywordDeleted
from .emojiKeywordsDifference import EmojiKeywordsDifference
from .emojiURL import EmojiURL
from .emojiLanguage import EmojiLanguage
from .folder import Folder
from .inputFolderPeer import InputFolderPeer
from .folderPeer import FolderPeer
from .urlAuthResultRequest import UrlAuthResultRequest
from .urlAuthResultAccepted import UrlAuthResultAccepted
from .channelLocation import ChannelLocation
from .peerLocated import PeerLocated
from .peerSelfLocated import PeerSelfLocated
from .restrictionReason import RestrictionReason
from .inputTheme import InputTheme
from .inputThemeSlug import InputThemeSlug
from .theme import Theme
from .inputThemeSettings import InputThemeSettings
from .themeSettings import ThemeSettings
from .webPageAttributeTheme import WebPageAttributeTheme
from .webPageAttributeStory import WebPageAttributeStory
from .webPageAttributeStickerSet import WebPageAttributeStickerSet
from .bankCardOpenUrl import BankCardOpenUrl
from .dialogFilter import DialogFilter
from .dialogFilterChatlist import DialogFilterChatlist
from .dialogFilterSuggested import DialogFilterSuggested
from .statsDateRangeDays import StatsDateRangeDays
from .statsAbsValueAndPrev import StatsAbsValueAndPrev
from .statsPercentValue import StatsPercentValue
from .statsGraphAsync import StatsGraphAsync
from .statsGraphError import StatsGraphError
from .statsGraph import StatsGraph
from .videoSize import VideoSize
from .videoSizeEmojiMarkup import VideoSizeEmojiMarkup
from .videoSizeStickerMarkup import VideoSizeStickerMarkup
from .statsGroupTopPoster import StatsGroupTopPoster
from .statsGroupTopAdmin import StatsGroupTopAdmin
from .statsGroupTopInviter import StatsGroupTopInviter
from .globalPrivacySettings import GlobalPrivacySettings
from .messageViews import MessageViews
from .messageReplyHeader import MessageReplyHeader
from .messageReplyStoryHeader import MessageReplyStoryHeader
from .messageReplies import MessageReplies
from .peerBlocked import PeerBlocked
from .groupCallDiscarded import GroupCallDiscarded
from .groupCall import GroupCall
from .inputGroupCall import InputGroupCall
from .groupCallParticipant import GroupCallParticipant
from .chatInviteImporter import ChatInviteImporter
from .chatAdminWithInvites import ChatAdminWithInvites
from .groupCallParticipantVideoSourceGroup import GroupCallParticipantVideoSourceGroup
from .groupCallParticipantVideo import GroupCallParticipantVideo
from .botCommandScopePeer import BotCommandScopePeer
from .botCommandScopePeerAdmins import BotCommandScopePeerAdmins
from .botCommandScopePeerUser import BotCommandScopePeerUser
from .sponsoredMessage import SponsoredMessage
from .searchResultsCalendarPeriod import SearchResultsCalendarPeriod
from .searchResultPosition import SearchResultPosition
from .reactionCount import ReactionCount
from .messageReactions import MessageReactions
from .availableReaction import AvailableReaction
from .messagePeerReaction import MessagePeerReaction
from .groupCallStreamChannel import GroupCallStreamChannel
from .attachMenuBotIconColor import AttachMenuBotIconColor
from .attachMenuBotIcon import AttachMenuBotIcon
from .attachMenuBot import AttachMenuBot
from .attachMenuBots import AttachMenuBots
from .attachMenuBotsBot import AttachMenuBotsBot
from .webViewResultUrl import WebViewResultUrl
from .simpleWebViewResultUrl import SimpleWebViewResultUrl
from .webViewMessageSent import WebViewMessageSent
from .botMenuButton import BotMenuButton
from .notificationSoundLocal import NotificationSoundLocal
from .notificationSoundRingtone import NotificationSoundRingtone
from .inputInvoiceMessage import InputInvoiceMessage
from .inputInvoiceSlug import InputInvoiceSlug
from .inputInvoicePremiumGiftCode import InputInvoicePremiumGiftCode
from .inputInvoiceStars import InputInvoiceStars
from .inputStorePaymentPremiumSubscription import InputStorePaymentPremiumSubscription
from .inputStorePaymentGiftPremium import InputStorePaymentGiftPremium
from .inputStorePaymentPremiumGiftCode import InputStorePaymentPremiumGiftCode
from .inputStorePaymentPremiumGiveaway import InputStorePaymentPremiumGiveaway
from .inputStorePaymentStars import InputStorePaymentStars
from .premiumGiftOption import PremiumGiftOption
from .paymentFormMethod import PaymentFormMethod
from .emojiStatus import EmojiStatus
from .emojiStatusUntil import EmojiStatusUntil
from .reactionEmoji import ReactionEmoji
from .reactionCustomEmoji import ReactionCustomEmoji
from .chatReactionsAll import ChatReactionsAll
from .chatReactionsSome import ChatReactionsSome
from .emailVerifyPurposeLoginSetup import EmailVerifyPurposeLoginSetup
from .emailVerificationCode import EmailVerificationCode
from .emailVerificationGoogle import EmailVerificationGoogle
from .emailVerificationApple import EmailVerificationApple
from .premiumSubscriptionOption import PremiumSubscriptionOption
from .sendAsPeer import SendAsPeer
from .messageExtendedMediaPreview import MessageExtendedMediaPreview
from .messageExtendedMedia import MessageExtendedMedia
from .stickerKeyword import StickerKeyword
from .username import Username
from .forumTopicDeleted import ForumTopicDeleted
from .forumTopic import ForumTopic
from .defaultHistoryTTL import DefaultHistoryTTL
from .exportedContactToken import ExportedContactToken
from .requestPeerTypeUser import RequestPeerTypeUser
from .requestPeerTypeChat import RequestPeerTypeChat
from .requestPeerTypeBroadcast import RequestPeerTypeBroadcast
from .emojiList import EmojiList
from .emojiGroup import EmojiGroup
from .emojiGroupGreeting import EmojiGroupGreeting
from .emojiGroupPremium import EmojiGroupPremium
from .textWithEntities import TextWithEntities
from .autoSaveSettings import AutoSaveSettings
from .autoSaveException import AutoSaveException
from .inputBotAppID import InputBotAppID
from .inputBotAppShortName import InputBotAppShortName
from .botApp import BotApp
from .appWebViewResultUrl import AppWebViewResultUrl
from .inlineBotWebView import InlineBotWebView
from .readParticipantDate import ReadParticipantDate
from .inputChatlistDialogFilter import InputChatlistDialogFilter
from .exportedChatlistInvite import ExportedChatlistInvite
from .messagePeerVote import MessagePeerVote
from .messagePeerVoteInputOption import MessagePeerVoteInputOption
from .messagePeerVoteMultiple import MessagePeerVoteMultiple
from .storyViews import StoryViews
from .storyItemDeleted import StoryItemDeleted
from .storyItemSkipped import StoryItemSkipped
from .storyItem import StoryItem
from .storyView import StoryView
from .storyViewPublicForward import StoryViewPublicForward
from .storyViewPublicRepost import StoryViewPublicRepost
from .inputReplyToMessage import InputReplyToMessage
from .inputReplyToStory import InputReplyToStory
from .exportedStoryLink import ExportedStoryLink
from .storiesStealthMode import StoriesStealthMode
from .mediaAreaCoordinates import MediaAreaCoordinates
from .mediaAreaVenue import MediaAreaVenue
from .inputMediaAreaVenue import InputMediaAreaVenue
from .mediaAreaGeoPoint import MediaAreaGeoPoint
from .mediaAreaSuggestedReaction import MediaAreaSuggestedReaction
from .mediaAreaChannelPost import MediaAreaChannelPost
from .inputMediaAreaChannelPost import InputMediaAreaChannelPost
from .peerStories import PeerStories
from .premiumGiftCodeOption import PremiumGiftCodeOption
from .prepaidGiveaway import PrepaidGiveaway
from .boost import Boost
from .myBoost import MyBoost
from .storyFwdHeader import StoryFwdHeader
from .postInteractionCountersMessage import PostInteractionCountersMessage
from .postInteractionCountersStory import PostInteractionCountersStory
from .publicForwardMessage import PublicForwardMessage
from .publicForwardStory import PublicForwardStory
from .peerColor import PeerColor
from .storyReaction import StoryReaction
from .storyReactionPublicForward import StoryReactionPublicForward
from .storyReactionPublicRepost import StoryReactionPublicRepost
from .savedDialog import SavedDialog
from .savedReactionTag import SavedReactionTag
from .outboxReadDate import OutboxReadDate
from .smsJob import SmsJob
from .businessWeeklyOpen import BusinessWeeklyOpen
from .businessWorkHours import BusinessWorkHours
from .businessLocation import BusinessLocation
from .inputBusinessRecipients import InputBusinessRecipients
from .businessRecipients import BusinessRecipients
from .businessAwayMessageScheduleCustom import BusinessAwayMessageScheduleCustom
from .inputBusinessGreetingMessage import InputBusinessGreetingMessage
from .businessGreetingMessage import BusinessGreetingMessage
from .inputBusinessAwayMessage import InputBusinessAwayMessage
from .businessAwayMessage import BusinessAwayMessage
from .timezone import Timezone
from .quickReply import QuickReply
from .inputQuickReplyShortcut import InputQuickReplyShortcut
from .inputQuickReplyShortcutId import InputQuickReplyShortcutId
from .connectedBot import ConnectedBot
from .birthday import Birthday
from .botBusinessConnection import BotBusinessConnection
from .inputBusinessIntro import InputBusinessIntro
from .businessIntro import BusinessIntro
from .inputCollectibleUsername import InputCollectibleUsername
from .inputCollectiblePhone import InputCollectiblePhone
from .inputBusinessBotRecipients import InputBusinessBotRecipients
from .businessBotRecipients import BusinessBotRecipients
from .contactBirthday import ContactBirthday
from .missingInvitee import MissingInvitee
from .inputBusinessChatLink import InputBusinessChatLink
from .businessChatLink import BusinessChatLink
from .requestedPeerUser import RequestedPeerUser
from .requestedPeerChat import RequestedPeerChat
from .requestedPeerChannel import RequestedPeerChannel
from .sponsoredMessageReportOption import SponsoredMessageReportOption
from .broadcastRevenueTransactionProceeds import BroadcastRevenueTransactionProceeds
from .broadcastRevenueTransactionWithdrawal import BroadcastRevenueTransactionWithdrawal
from .broadcastRevenueTransactionRefund import BroadcastRevenueTransactionRefund
from .reactionsNotifySettings import ReactionsNotifySettings
from .broadcastRevenueBalances import BroadcastRevenueBalances
from .availableEffect import AvailableEffect
from .factCheck import FactCheck
from .starsTransactionPeer import StarsTransactionPeer
from .starsTopupOption import StarsTopupOption
from .starsTransaction import StarsTransaction
