
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-06-04T15:14:16-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "867543a894e180bbd2d52066ab60deabb7bf4519",
 "version": "2.19.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
