# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

from .problem_body_content import ProblemBodyContent
from .problem_null_unicode import ProblemNullUnicode
from .problem_validation import ProblemValidation


class BadRequestErrorBody_BadRequestBodyContent(ProblemBodyContent):
    type: typing.Literal["/bad-request/body-content"]

    class Config:
        frozen = True
        smart_union = True
        allow_population_by_field_name = True


class BadRequestErrorBody_BadRequestHasNullUnicodeCharacter(ProblemNullUnicode):
    type: typing.Literal["/bad-request/has-null-unicode-character"]

    class Config:
        frozen = True
        smart_union = True
        allow_population_by_field_name = True


class BadRequestErrorBody_BadRequestValidation(ProblemValidation):
    type: typing.Literal["/bad-request/validation"]

    class Config:
        frozen = True
        smart_union = True
        allow_population_by_field_name = True


BadRequestErrorBody = typing.Union[
    BadRequestErrorBody_BadRequestBodyContent,
    BadRequestErrorBody_BadRequestHasNullUnicodeCharacter,
    BadRequestErrorBody_BadRequestValidation,
]
