# This file was auto-generated by Fern from our API Definition.

import enum
import typing

T_Result = typing.TypeVar("T_Result")


class PresentationField(str, enum.Enum):
    """
    Enum of all available values.
    """

    KIND_NAME = "KIND_NAME"
    ID = "ID"
    REVISION = "REVISION"
    CREATED_AT = "CREATED_AT"
    MODIFIED_AT = "MODIFIED_AT"
    ETAG = "ETAG"
    DATA_ID = "DATA_ID"
    DELETED_AT = "DELETED_AT"

    def visit(
        self,
        kind_name: typing.Callable[[], T_Result],
        id: typing.Callable[[], T_Result],
        revision: typing.Callable[[], T_Result],
        created_at: typing.Callable[[], T_Result],
        modified_at: typing.Callable[[], T_Result],
        etag: typing.Callable[[], T_Result],
        data_id: typing.Callable[[], T_Result],
        deleted_at: typing.Callable[[], T_Result],
    ) -> T_Result:
        if self is PresentationField.KIND_NAME:
            return kind_name()
        if self is PresentationField.ID:
            return id()
        if self is PresentationField.REVISION:
            return revision()
        if self is PresentationField.CREATED_AT:
            return created_at()
        if self is PresentationField.MODIFIED_AT:
            return modified_at()
        if self is PresentationField.ETAG:
            return etag()
        if self is PresentationField.DATA_ID:
            return data_id()
        if self is PresentationField.DELETED_AT:
            return deleted_at()
