
# This file was generated by 'versioneer.py' (0.23.dev0) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-06-06T21:22:18+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "c88b0a6e7b85cc542d1be80b2a285ad1393296c0",
 "version": "1.0.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
