import typing
import collections.abc

GenericType1 = typing.TypeVar("GenericType1")
GenericType2 = typing.TypeVar("GenericType2")

def keyconfig_export(wm, kc, filepath): ...
def keyconfig_export(wm, kc, filepath): ...
def keyconfig_merge(kc1, kc2):
    """note: kc1 takes priority over kc2"""

    ...

def keyconfig_merge(kc1, kc2):
    """note: kc1 takes priority over kc2"""

    ...

def keyconfig_test(kc): ...
def keyconfig_test(kc): ...
def km_exists_in(km, export_keymaps): ...
def km_exists_in(km, export_keymaps): ...
