import os

WF_AUTH0_GOOGLE_WORKSPACE_API_AUDIENCE = os.getenv("WF_AUTH0_GOOGLE_WORKSPACE_API_AUDIENCE", None)

WF_AUTH0_DOMAIN = os.getenv("WF_AUTH0_DOMAIN", None)

WF_AUTH0_CLIENT_ID = os.getenv("WF_AUTH0_CLIENT_ID", None)

WF_AUTH0_CLIENT_SECRET = os.getenv("WF_AUTH0_CLIENT_SECRET", None)

WF_GOOGLE_WORKSPACE_API_URL = os.getenv("WF_GOOGLE_WORKSPACE_API_URL", None)
