
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-06-04T11:19:00+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "93e7aefc50c667bb400a17b1ec8ed53224de23d0",
 "version": "0.8.0b3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
