import typing
import collections.abc

GenericType1 = typing.TypeVar("GenericType1")
GenericType2 = typing.TypeVar("GenericType2")

def add_scrollback(text, text_type): ...
def autocomplete(context): ...
def banner(context): ...
def execute(context, is_interactive): ...
def shell_run(text): ...
