import multiprocessing.queues
import threading
from _typeshed import Incomplete
from eventlet.green import threading as eventlet_threading

class _RxThread(threading.Thread):
    def __init__(self, rx_queue, exit_event, error_queue) -> None: ...
    def run(self) -> None: ...

class Streamer:
    def __init__(self, queue_depth: int = ..., inter_msg_time: int = ..., drop_frames: bool = ..., max_image_width: int = ..., max_image_height: int = ..., **kwargs) -> None: ...
    def setup(self): ...
    def send_data(self, image: Incomplete | None = ..., text: Incomplete | None = ...) -> None: ...
    def wait(self) -> None: ...
    def check_exit(self): ...
    def close(self) -> None: ...
    def __enter__(self): ...
    def __exit__(self, type, value, traceback) -> None: ...
    def __del__(self) -> None: ...

class _TxThread(eventlet_threading.Thread):
    def __init__(self, tx_queue, inter_msg_time, max_image_width, max_image_height, jpg_quality, error_queue) -> None: ...
    def run(self) -> None: ...

class _ServerProcess(multiprocessing.Process):
    def __init__(self, ipaddr, port, tx_queue, inter_msg_time, max_image_width, max_image_height, jpg_quality, rx_queue, error_queue, *args, **kwargs) -> None: ...
    def run(self) -> None: ...
