# This file was auto-generated by Fern from our API Definition.

import typing

InstanceTerm = typing.Union[
    typing.Literal["hourly", "weekly", "monthly", "quarterly", "six_monthly", "yearly"], typing.Any
]
