model_map = {

    "amazon.titan-text-express-v1": "Amazon",
    "amazon.titan-text-lite-v1": "Amazon",
    "amazon.titan-text-premier-v1:0": "Amazon",
    "anthropic.claude-v2": "Anthropic",
    "anthropic.claude-v2:1": "Anthropic",
    "anthropic.claude-3-sonnet-20240229-v1:0": "Anthropic",
    "anthropic.claude-3-haiku-20240307-v1:0": "Anthropic",
    "anthropic.claude-3-opus-20240229-v1:0": "Anthropic",
    "anthropic.claude-instant-v1": "Anthropic",
    "cohere.command-text-v14": "Cohere",
    "cohere.command-light-text-v14": "Cohere",
    "cohere.command-r-v1:0": "Cohere",
    "cohere.command-r-plus-v1:0": "Cohere",
    "meta.llama2-13b-chat-v1": "Meta",
    "meta.llama2-70b-chat-v1": "Meta",
    "meta.llama3-8b-instruct-v1:0": "Meta",
    "meta.llama3-70b-instruct-v1:0": "Meta",
    "mistral.mistral-7b-instruct-v0:2": "Mistral AI",
    "mistral.mixtral-8x7b-instruct-v0:1": "Mistral AI",
    "mistral.mistral-large-2402-v1:0": "Mistral AI",
    "mistral.mistral-small-2402-v1:0": "Mistral AI",

}