# Generated by Django 3.2.5 on 2022-01-24 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qronos_django', '0002_auto_20201102_0813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qronosimportlog',
            name='import_type',
            field=models.CharField(choices=[('Tracker', 'Tracker'), ('Stage', 'Stage'), ('TrackerStage', 'TrackerStage'), ('Delete', 'Delete')], max_length=20),
        ),
    ]
