
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-06-05T14:00:33-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "8816a2f9bf0ea4be0b8d50af93855b9a29975b30",
 "version": "5.2.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
