# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: yandex/cloud/priv/iam/v1/console/membership_service.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from yandex.cloud.priv.oauth import claims_pb2 as yandex_dot_cloud_dot_priv_dot_oauth_dot_claims__pb2
from yandex.cloud.priv import validation_pb2 as yandex_dot_cloud_dot_priv_dot_validation__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n9yandex/cloud/priv/iam/v1/console/membership_service.proto\x12 yandex.cloud.priv.iam.v1.console\x1a$yandex/cloud/priv/oauth/claims.proto\x1a\"yandex/cloud/priv/validation.proto\"\xc8\x01\n\x12ListMembersRequest\x12#\n\x0forganization_id\x18\x01 \x01(\tB\x08\xca\x89\x31\x04<=50H\x00\x12\x1c\n\x08\x63loud_id\x18\x02 \x01(\tB\x08\xca\x89\x31\x04<=50H\x00\x12\x1a\n\x06\x66ilter\x18\x03 \x01(\tB\n\xca\x89\x31\x06<=1000\x12\x1d\n\tpage_size\x18\x04 \x01(\x03\x42\n\xba\x89\x31\x06<=1000\x12\x1e\n\npage_token\x18\x05 \x01(\tB\n\xca\x89\x31\x06<=2000B\x14\n\x0clist_context\x12\x04\x80\x83\x31\x01\"t\n\x13ListMembersResponse\x12\x44\n\x07members\x18\x01 \x03(\x0b\x32\x33.yandex.cloud.priv.iam.v1.console.SubjectWithClaims\x12\x17\n\x0fnext_page_token\x18\x02 \x01(\t\"S\n\x11SubjectWithClaims\x12>\n\x0esubject_claims\x18\x01 \x01(\x0b\x32&.yandex.cloud.priv.oauth.SubjectClaims2\x8f\x01\n\x11MembershipService\x12z\n\x0bListMembers\x12\x34.yandex.cloud.priv.iam.v1.console.ListMembersRequest\x1a\x35.yandex.cloud.priv.iam.v1.console.ListMembersResponseB\x13\x42\x04PCMSZ\x0biam_consoleb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'yandex.cloud.priv.iam.v1.console.membership_service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'B\004PCMSZ\013iam_console'
  _globals['_LISTMEMBERSREQUEST'].oneofs_by_name['list_context']._options = None
  _globals['_LISTMEMBERSREQUEST'].oneofs_by_name['list_context']._serialized_options = b'\200\2031\001'
  _globals['_LISTMEMBERSREQUEST'].fields_by_name['organization_id']._options = None
  _globals['_LISTMEMBERSREQUEST'].fields_by_name['organization_id']._serialized_options = b'\312\2111\004<=50'
  _globals['_LISTMEMBERSREQUEST'].fields_by_name['cloud_id']._options = None
  _globals['_LISTMEMBERSREQUEST'].fields_by_name['cloud_id']._serialized_options = b'\312\2111\004<=50'
  _globals['_LISTMEMBERSREQUEST'].fields_by_name['filter']._options = None
  _globals['_LISTMEMBERSREQUEST'].fields_by_name['filter']._serialized_options = b'\312\2111\006<=1000'
  _globals['_LISTMEMBERSREQUEST'].fields_by_name['page_size']._options = None
  _globals['_LISTMEMBERSREQUEST'].fields_by_name['page_size']._serialized_options = b'\272\2111\006<=1000'
  _globals['_LISTMEMBERSREQUEST'].fields_by_name['page_token']._options = None
  _globals['_LISTMEMBERSREQUEST'].fields_by_name['page_token']._serialized_options = b'\312\2111\006<=2000'
  _globals['_LISTMEMBERSREQUEST']._serialized_start=170
  _globals['_LISTMEMBERSREQUEST']._serialized_end=370
  _globals['_LISTMEMBERSRESPONSE']._serialized_start=372
  _globals['_LISTMEMBERSRESPONSE']._serialized_end=488
  _globals['_SUBJECTWITHCLAIMS']._serialized_start=490
  _globals['_SUBJECTWITHCLAIMS']._serialized_end=573
  _globals['_MEMBERSHIPSERVICE']._serialized_start=576
  _globals['_MEMBERSHIPSERVICE']._serialized_end=719
# @@protoc_insertion_point(module_scope)
