agencies_dict = {
    "Leo Burnett": ["Leo Burnett"],
    "Razorfish": ["Razorfish", "RZF"],
    "Saatchi & Saatchi": ["Saatchi & Saatchi"],
    "Saatchi & Saatchi Wellness": ["Saatchi & Saatchi Wellness"],
    "Publicis Health": ["Publicis Health", "Pub Health"],
    "Razorfish Health": ["Razorfish Health"],
    "Publicis Worldwide": ["Publicis Worldwide", "Pub Worldwide"],
    "Publicis Sports & Entertainment": [
        "Publicis Sports & Entertainment",
        "Pub Sports & Entertainment",
        "PSE",
    ],
    "Publicis Media": ["Publicis Media", "Pub Media"],
    "Publicis Commerce": ["Publicis Commerce", "Pub Commerce"],
    "Publicis Content": ["Publicis Content", "Pub Content"],
    "Publicis Poke": ["Publicis Poke", "Pub Poke"],
    "Publicis Production": ["Publicis Production", "Pub Production"],
    "Publicis Sapient": ["Publicis Sapient", "Pub Sapient", "PS", "Sapient"],
    "Profitero": ["Profitero"],
    "ARC": ["ARC"],
    "Digitas": ["Digitas"],
    "Digitas Health": ["Digitas Health"],
    "Fallon": ["Fallon"],
    "KEKST CNC": ["KEKST CNC"],
    "Langland": ["Langland"],
    "Octopus Group": ["Octopus Group"],
    "Performics": ["Performics"],
    "Epsilon": ["Epsilon"],
    "Hawkeye": ["Hawkeye"],
    "CitrusAD": ["CitrusAD"],
    "Prodigous": ["Prodigous"],
    "BBK": ["BBK"],
    "Harbor": ["Harbor"],
    "PXP": ["PXP Studios", "PXP"],
    "Salterbaxter": ["Salterbaxter"],
    "Spark Foundry": ["Spark Foundry"],
    "The Community": ["The Community"],
    "Taylor Herring": ["Taylor Herring"],
    "Boomerang": ["Boomerang"],
    "Turner Duckworth": ["Turner Duckworth"],
    "Meta Design": ["Meta Design"],
    "3 Share": ["3 Share"],
    "MSL Group": ["MSL Group", "MSL"],
    "Starcom": ["Starcom"],
    "Zenith": ["Zenith"],
    "BBH (Bartle Bogle Hegarty)": [
        "BBH (Bartle Bogle Hegarty)",
        "BBH",
        "Bartle Bogle Hegarty",
    ],
    "Publicis Digital Experience": ["Publicis Digital Experience", "PDX"],
}


regions_dict = {
    "North America": ["North America", "NA"],
    "LATAM": ["LATAM", "Latin America"],
    "EMEA": ["EMEA", "Europe", "Middle East", "Africa", "EU"],
    "APAC": ["APAC", "Asia", "the Pacific Region countries"],
    "India": ["India"],
}


partners_involved_dict = {
    "Adobe": ["Adobe"],
    "Salesforce": ["Salesforce"],
    "Google": ["Google", "GCP"],
    "Oracle": ["Oracle"],
    "IBM": ["IBM"],
    "Microsoft": ["Microsoft", "MSFT", "Azure"],
    "SAP": ["SAP"],
    "Amazon Web Services": ["Amazon Web Services", "AWS"],
}


industries_dict = {
    "Automative": [
        "Automative",
        "Automotive",
        "Auto",
        "Cars",
        "Vehicles",
        "Trucks",
        "Motorcycles",
    ],
    "CPG": [
        "CPG",
        "Consumer Products",
        "Consumer Packaged Goods",
        "Consumer Goods",
        "Consumer",
        "Beauty",
        "Food & Beverage",
        "Personal Care",
        "Household",
        "Personal Care & Beauty",
        "Personal Care Products",
    ],
    "Retail": [
        "Retail",
        "E-commerce",
        "Retail & E-commerce",
        "E-commerce & Retail",
        "Retail & Ecommerce",
    ],
    "Transportation & Mobility": [
        "Transportation & Mobility",
        "Transportation",
        "Mobility",
    ],
    "Travel & Hospitality": [
        "Travel & Hospitality",
        "Hospitality & Tourism",
        "Resturants",
        "QSR",
        "Hotels",
        "Tourism",
        "Travel",
        "Hospitality",
        "Travel & Tourism",
        "Travel & Leisure",
        "Travel & Transport",
        "Travel & Tourism",
    ],
    "Telecommunications": ["Telecommunications", "Telecom", "Telco"],
    "Media & Technology": [
        "Media & Technology",
        "TMT",
        "Media Industry",
        "Technology Industry",
        "Tech Industry",
        "Media & Entertainment",
    ],
    "Health": [
        "Health",
        "Healthcare",
        "Pharma",
        "Medical Devices",
        "Hospitals",
        "Pharma / Life Sciences",
        "Pharmaceutical",
        "Health & Wellness",
        "Theraupetics",
    ],
    "Energy & Commodities": [
        "Energy & Commodities",
        "Oil & Gas",
        "Mining",
        "Utilities",
        "Commodities",
        "Energy",
        "Renewable Energy",
    ],
    "Financial Services": [
        "Financial Services",
        "FinServ",
        "Banking",
        "Retail Banking",
        "Bank",
        "Insurance",
        "Fintech",
        "Wealth Management",
        "Capital Markets",
        "Financial",
        "Financial Institutions",
        "FSI",
    ],
}


acronym_to_full_names_dict = {
    "CPG": "Consumer Packaged Goods",
    "TMT": "Media & Technology",
    "PDX": "Publicis Digital Experience",
    "PS": "Publicis Sapient",
    "RZF": "Razorfish",
    "BBH": "Bartle Bogle Hegarty",
    "TH": "Travel & Hospitality",
    "DTC": "Direct-to-Consumer",
    "CX": "Customer Experience",
    "UX": "User Experience",
    "UI": "User Interface",
    "DX": "Digital Experience",
    "DBT": "Digital Business Transformation",
    "AI": "Artificial Intelligence",
    "ML": "Machine Learning",
    "DL": "Deep Learning",
    "NLP": "Natural Language Processing",
    "VR": "Virtual Reality",
    "AR": "Augmented Reality",
    "FSI": "Financial Services Industry",
}


synonyms = {
    "Omnichannel": ["Omnichannel", "Omni-channel", "Omni channel"],
    "Data driven": ["data-led", "data led", "data-driven"],
    "First party": ["first-party", "1P", "1st party"],
}


capabilities_services_dict = {
    "Digital Business Transformation": {
        "Digital Business Transformation": [
            "Digital Business Transformation",
            "Digital Transformation",
            "Business Transformation",
            "DBT",
        ],
        "Innovation & Digital Product Management": [
            "Innovation & Digital Product Management"
        ],
        "Data/AI Optimized Platforms/Systems": ["Data/AI Optimized Platforms/Systems"],
        "Enterprise Platforms": ["Enterprise Platforms", "Enterprise Data Platform"],
        "Platform Technology & Engineering": ["Platform Technology & Engineering"],
        "Customer Experience & Design": ["Customer Experience & Design"],
        "Digital Customer Experience": ["Digital Customer Experience"],
        "Strategy & Consulting": ["Strategy & Consulting"],
        "Digital Strategy": ["Digital Strategy"],
        "Digital Maturity": ["Digital Maturity"],
    },
    "Commerce": {
        "Shopper Marketing & Activation": ["Shopper Marketing & Activation"],
        "Commerce Consulting": ["Commerce Consulting"],
        "Commerce platforms": ["Commerce platforms"],
        "Commerce Experience": ["Commerce Experience"],
        "Commerce Media": ["Commerce Media"],
        "Enterprise Strategy": ["Enterprise Strategy"],
    },
    "Health": {
        "Data-led Health Insight": [
            "Data-led Health Insight",
            "Data-led Health",
            "Data-driven Health",
        ],
        "Strategy & Measurement": ["Strategy & Measurement"],
        "Category Creative & Experience": ["Category Creative & Experience"],
        "Omnichannel Health & Wellness Media": ["Omnichannel Health & Wellness Media"],
        "Health Service Design & CRM": ["Health Service Design & CRM"],
        "Clinical Trial Experience": ["Clinical Trial Experience"],
        "Market Access": ["Market Access"],
        "Public Relations & Medical Education": [
            "Public Relations & Medical Education"
        ],
        "Accelerated Approval": ["Accelerated Approval"],
        "Rx Products": ["Rx Product", "Rx"],
        "Point of Care Channel Experience": [
            "Point of Care Channel Experience",
            "Point of Care Channel",
        ],
    },
    "ESG": {
        "Sustainability Insights": ["Sustainability Insights"],
        "Strategy & Marketing": ["Strategy & Marketing"],
        "Purpose Strategy & Consulting": ["Purpose Strategy & Consulting"],
        "Corporate Responsibility Reporting": ["Corporate Responsibility Reporting"],
        "Diversity & Inclusion / Multi Cultural Marketing": [
            "Diversity & Inclusion / Multi Cultural Marketing"
        ],
    },
    "Agile Production & Development": {
        "Automation": ["Automation"],
        "Dynamic Assembly": ["Dynamic Assembly"],
        "Production Distribution": ["Production Distribution"],
        "Production Optimization": ["Production Optimization"],
        "Digital Asset Management & Workflow": ["Digital Asset Management & Workflow"],
        "Digital Production": ["Digital Production"],
        "Language Services": ["Language Services"],
        "Adaptation/Localization": ["Adaptation/Localization"],
        "Production Origination": ["Production Origination"],
    },
    "Content": {
        "Content Intelligence": ["Content Intelligence"],
        "Strategy & Consulting": ["Strategy & Consulting"],
        "Social Media Management": [
            "Social Media Management",
            "Social",
            "Social Media",
        ],
        "Influencer Marketing": ["Influencer Marketing"],
        "Media, Gaming, Metaverse & Entertainment Partnerships": [
            "Media, Gaming, Metaverse & Entertainment Partnerships"
        ],
        "Sports Partnerships": ["Sports Partnerships"],
        "Content Distribution": ["Content Distribution"],
        "Dynamic Creative Optimization": [
            "DCO (Dynamic Creative Optimization)",
            "DCO",
            "Dynamic Creative Optimization",
        ],
    },
    "Media Performance": {
        "Strategy & Planning": ["Strategy & Planning"],
        "Programmatic Media Buying": ["Programmatic Media Buying"],
        "Performance Marketing": ["Performance Marketing"],
        "SEO Marketing": ["SEO Marketing"],
        "Attribution & Measurement": ["Attribution & Measurement"],
        "Social Listening": ["Social Listening"],
        "Media Planning": ["Media Planning"],
        "Media Strategy": ["Media Strategy"],
        "Media Planning & Buying": ["Media Planning & Buying"],
        "Media Buying": ["Media Buying"],
        "Programmatic Media Buying": ["Programmatic Media Buying"],
        "Performance Marketing": ["Performance Marketing"],
        "SEO Marketing": ["SEO Marketing"],
        "Attribution & Measurement": ["Attribution & Measurement"],
        "Social Listening": ["Social Listening"],
        "Media Optimizations": [
            "Campaign optimization",
            "Media Optimization",
            "Campaign/Media Optimization",
            "Dynamic Creative Optimzation",
        ],
        "Campaign Execution": ["Campaign Execution"],
        "Omnichannel Campaign": ["Omnichannel Campaign"],
        "Omnichannel Marketing": ["Omnichannel Marketing"],
        "Omnichannel Strategy": ["Omnichannel Strategy"],
        "Audience Segmentation": ["Audience Segmentation"],
        "Consumer Media Campaign": ["Consumer Media Campaign"],
        "Launch Campaign": [
            "Launch Campaign",
            "Brand Launch",
            "Product Launch",
            "Launch",
        ],
        "Personalization Strategy": ["Personalization Strategy"],
        "Customer Engagement Strategy": ["Customer Engagement Strategy"],
        "Audiennce-Led Planning": ["Audiennce-Led Planning"],
    },
    "Reputation & Influence": {
        "Consumer PR": ["Consumer PR"],
        "Corporate PR": ["Corporate PR"],
        "Employee Engagement": ["Employee Engagement"],
        "Events & Activations": ["Events & Activations"],
        "Influencer Management": ["Influencer Management"],
    },
    "Brand Building Creative": {
        "Brand Strategy": ["Brand Strategy"],
        "Experience Design": ["Experience Design"],
        "Advertising": ["Advertising"],
        "Portfolio Management": ["Portfolio Management"],
        "UX Design": ["UX Design"],
        "Brand & VI Systems Design": ["Brand & VI Systems Design"],
        "Brand Performance": ["Brand Performance"],
        "Program Design": ["Program Design"],
        "Brand Portfolio Management": [
            "Brand Portfolio Management",
            "Brand Portfolio",
            "Brand Management",
        ],
    },
    "Data Strategy & Activation": {
        "Data Platforms & Insights": ["Data Platforms & Insights"],
        "Identity": ["Identity"],
        "Data Strategy & Development": ["Data Strategy & Development"],
        "Dynamic Content Engine": ["Dynamic Content Engine"],
        "Messaging & Loyalty": ["Messaging & Loyalty"],
        "Digital Media Solutions": ["Digital Media Solutions"],
        "CRM": ["CRM", "Customer Relationship Management"],
        "Data Strategy": ["Data Strategy"],
        "Data Activation": ["Data Activation"],
        "Data Driven Decisions": ["Data Driven Decisions", "Data Driven"],
        "Measurement Framework": ["Measurement Framework", "Real-time Measurement"],
        "Emotional Loyalty": ["Emotional Loyalty"],
        "Loyalty Strategy": ["Loyalty Strategy", "Loyalty Program", "Loyalty"],
    },
}


countries_dict = {
    "Afghanistan": ["Afghanistan"],
    "Åland Islands": ["Åland Islands"],
    "Albania": ["Albania"],
    "Algeria": ["Algeria"],
    "American Samoa": ["American Samoa"],
    "Andorra": ["Andorra"],
    "Angola": ["Angola"],
    "Anguilla": ["Anguilla"],
    "Antarctica": ["Antarctica"],
    "Antigua & Barbuda": ["Antigua & Barbuda"],
    "Argentina": ["Argentina"],
    "Armenia": ["Armenia"],
    "Aruba": ["Aruba"],
    "Australia": ["Australia"],
    "Austria": ["Austria"],
    "Azerbaijan": ["Azerbaijan"],
    "Bahamas": ["Bahamas"],
    "Bahrain": ["Bahrain"],
    "Bangladesh": ["Bangladesh"],
    "Barbados": ["Barbados"],
    "Belarus": ["Belarus"],
    "Belgium": ["Belgium"],
    "Belize": ["Belize"],
    "Benin": ["Benin"],
    "Bermuda": ["Bermuda"],
    "Bhutan": ["Bhutan"],
    "Bolivia": ["Bolivia"],
    "Bosnia & Herzegovina": ["Bosnia & Herzegovina"],
    "Botswana": ["Botswana"],
    "Bouvet Island": ["Bouvet Island"],
    "Brazil": ["Brazil"],
    "British Indian Ocean Territory": ["British Indian Ocean Territory"],
    "British Virgin Islands": ["British Virgin Islands"],
    "Brunei": ["Brunei"],
    "Bulgaria": ["Bulgaria"],
    "Burkina Faso": ["Burkina Faso"],
    "Burundi": ["Burundi"],
    "Cambodia": ["Cambodia"],
    "Cameroon": ["Cameroon"],
    "Canada": ["Canada"],
    "Cape Verde": ["Cape Verde"],
    "Caribbean Netherlands": ["Caribbean Netherlands"],
    "Cayman Islands": ["Cayman Islands"],
    "Central African Republic": ["Central African Republic"],
    "Chad": ["Chad"],
    "Chile": ["Chile"],
    "China": ["China"],
    "Christmas Island": ["Christmas Island"],
    "Cocos (Keeling) Islands": ["Cocos (Keeling) Islands"],
    "Colombia": ["Colombia"],
    "Comoros": ["Comoros"],
    "Congo - Brazzaville": ["Congo - Brazzaville"],
    "Congo - Kinshasa": ["Congo - Kinshasa"],
    "Cook Islands": ["Cook Islands"],
    "Costa Rica": ["Costa Rica"],
    "Côte d’Ivoire": ["Côte d’Ivoire"],
    "Croatia": ["Croatia"],
    "Cuba": ["Cuba"],
    "Curaçao": ["Curaçao"],
    "Cyprus": ["Cyprus"],
    "Czechia": ["Czechia"],
    "Denmark": ["Denmark"],
    "Djibouti": ["Djibouti"],
    "Dominica": ["Dominica"],
    "Dominican Republic": ["Dominican Republic"],
    "Ecuador": ["Ecuador"],
    "Egypt": ["Egypt"],
    "El Salvador": ["El Salvador"],
    "Equatorial Guinea": ["Equatorial Guinea"],
    "Eritrea": ["Eritrea"],
    "Estonia": ["Estonia"],
    "Eswatini": ["Eswatini"],
    "Ethiopia": ["Ethiopia"],
    "Falkland Islands": ["Falkland Islands"],
    "Faroe Islands": ["Faroe Islands"],
    "Fiji": ["Fiji"],
    "Finland": ["Finland"],
    "France": ["France"],
    "French Guiana": ["French Guiana"],
    "French Polynesia": ["French Polynesia"],
    "French Southern Territories": ["French Southern Territories"],
    "Gabon": ["Gabon"],
    "Gambia": ["Gambia"],
    "Georgia": ["Georgia"],
    "Germany": ["Germany"],
    "Ghana": ["Ghana"],
    "Gibraltar": ["Gibraltar"],
    "Greece": ["Greece"],
    "Greenland": ["Greenland"],
    "Grenada": ["Grenada"],
    "Guadeloupe": ["Guadeloupe"],
    "Guam": ["Guam"],
    "Guatemala": ["Guatemala"],
    "Guernsey": ["Guernsey"],
    "Guinea": ["Guinea"],
    "Guinea-Bissau": ["Guinea-Bissau"],
    "Guyana": ["Guyana"],
    "Haiti": ["Haiti"],
    "Heard & McDonald Islands": ["Heard & McDonald Islands"],
    "Honduras": ["Honduras"],
    "Hong Kong SAR China": ["Hong Kong SAR China"],
    "Hungary": ["Hungary"],
    "Iceland": ["Iceland"],
    "India": ["India"],
    "Indonesia": ["Indonesia"],
    "Iran": ["Iran"],
    "Iraq": ["Iraq"],
    "Ireland": ["Ireland"],
    "Isle of Man": ["Isle of Man"],
    "Israel": ["Israel"],
    "Italy": ["Italy"],
    "Jamaica": ["Jamaica"],
    "Japan": ["Japan"],
    "Jersey": ["Jersey"],
    "Jordan": ["Jordan"],
    "Kazakhstan": ["Kazakhstan"],
    "Kenya": ["Kenya"],
    "Kiribati": ["Kiribati"],
    "Kuwait": ["Kuwait"],
    "Kyrgyzstan": ["Kyrgyzstan"],
    "Laos": ["Laos"],
    "Latvia": ["Latvia"],
    "Lebanon": ["Lebanon"],
    "Lesotho": ["Lesotho"],
    "Liberia": ["Liberia"],
    "Libya": ["Libya"],
    "Liechtenstein": ["Liechtenstein"],
    "Lithuania": ["Lithuania"],
    "Luxembourg": ["Luxembourg"],
    "Macao SAR China": ["Macao SAR China"],
    "Madagascar": ["Madagascar"],
    "Malawi": ["Malawi"],
    "Malaysia": ["Malaysia"],
    "Maldives": ["Maldives"],
    "Mali": ["Mali"],
    "Malta": ["Malta"],
    "Marshall Islands": ["Marshall Islands"],
    "Martinique": ["Martinique"],
    "Mauritania": ["Mauritania"],
    "Mauritius": ["Mauritius"],
    "Mayotte": ["Mayotte"],
    "Mexico": ["Mexico"],
    "Micronesia": ["Micronesia"],
    "Moldova": ["Moldova"],
    "Monaco": ["Monaco"],
    "Mongolia": ["Mongolia"],
    "Montenegro": ["Montenegro"],
    "Montserrat": ["Montserrat"],
    "Morocco": ["Morocco"],
    "Mozambique": ["Mozambique"],
    "Myanmar (Burma)": ["Myanmar (Burma)"],
    "Namibia": ["Namibia"],
    "Nauru": ["Nauru"],
    "Nepal": ["Nepal"],
    "Netherlands": ["Netherlands"],
    "New Caledonia": ["New Caledonia"],
    "New Zealand": ["New Zealand"],
    "Nicaragua": ["Nicaragua"],
    "Niger": ["Niger"],
    "Nigeria": ["Nigeria"],
    "Niue": ["Niue"],
    "Norfolk Island": ["Norfolk Island"],
    "North Korea": ["North Korea"],
    "North Macedonia": ["North Macedonia"],
    "Northern Mariana Islands": ["Northern Mariana Islands"],
    "Norway": ["Norway"],
    "Oman": ["Oman"],
    "Pakistan": ["Pakistan"],
    "Palau": ["Palau"],
    "Palestinian Territories": ["Palestinian Territories"],
    "Panama": ["Panama"],
    "Papua New Guinea": ["Papua New Guinea"],
    "Paraguay": ["Paraguay"],
    "Peru": ["Peru"],
    "Philippines": ["Philippines"],
    "Pitcairn Islands": ["Pitcairn Islands"],
    "Poland": ["Poland"],
    "Portugal": ["Portugal"],
    "Puerto Rico": ["Puerto Rico"],
    "Qatar": ["Qatar"],
    "Réunion": ["Réunion"],
    "Romania": ["Romania"],
    "Russia": ["Russia"],
    "Rwanda": ["Rwanda"],
    "Samoa": ["Samoa"],
    "San Marino": ["San Marino"],
    "São Tomé & Príncipe": ["São Tomé & Príncipe"],
    "Saudi Arabia": ["Saudi Arabia"],
    "Senegal": ["Senegal"],
    "Serbia": ["Serbia"],
    "Seychelles": ["Seychelles"],
    "Sierra Leone": ["Sierra Leone"],
    "Singapore": ["Singapore"],
    "Sint Maarten": ["Sint Maarten"],
    "Slovakia": ["Slovakia"],
    "Slovenia": ["Slovenia"],
    "Solomon Islands": ["Solomon Islands"],
    "Somalia": ["Somalia"],
    "South Africa": ["South Africa"],
    "South Georgia & South Sandwich Islands": [
        "South Georgia & South Sandwich Islands"
    ],
    "South Korea": ["South Korea"],
    "South Sudan": ["South Sudan"],
    "Spain": ["Spain"],
    "Sri Lanka": ["Sri Lanka"],
    "St. Barthélemy": ["St. Barthélemy"],
    "St. Helena": ["St. Helena"],
    "St. Kitts & Nevis": ["St. Kitts & Nevis"],
    "St. Lucia": ["St. Lucia"],
    "St. Martin": ["St. Martin"],
    "St. Pierre & Miquelon": ["St. Pierre & Miquelon"],
    "St. Vincent & Grenadines": ["St. Vincent & Grenadines"],
    "Sudan": ["Sudan"],
    "Suriname": ["Suriname"],
    "Svalbard & Jan Mayen": ["Svalbard & Jan Mayen"],
    "Sweden": ["Sweden"],
    "Switzerland": ["Switzerland"],
    "Syria": ["Syria"],
    "Taiwan": ["Taiwan"],
    "Tajikistan": ["Tajikistan"],
    "Tanzania": ["Tanzania"],
    "Thailand": ["Thailand"],
    "Timor-Leste": ["Timor-Leste"],
    "Togo": ["Togo"],
    "Tokelau": ["Tokelau"],
    "Tonga": ["Tonga"],
    "Trinidad & Tobago": ["Trinidad & Tobago"],
    "Tunisia": ["Tunisia"],
    "Turkey": ["Turkey"],
    "Turkmenistan": ["Turkmenistan"],
    "Turks & Caicos Islands": ["Turks & Caicos Islands"],
    "Tuvalu": ["Tuvalu"],
    "U.S. Outlying Islands": ["U.S. Outlying Islands"],
    "U.S. Virgin Islands": ["U.S. Virgin Islands"],
    "Uganda": ["Uganda"],
    "Ukraine": ["Ukraine"],
    "United Arab Emirates": ["United Arab Emirates", "UAE", "Dubai"],
    "United Kingdom": [
        "United Kingdom",
        "the UK",
        "England",
        "Scotland",
        "Wales",
        "Northern Ireland",
        "Great Britain",
        "Britain",
        "British Isles",
    ],
    "United States": ["United States", "the US", "USA", "America"],
    "Uruguay": ["Uruguay"],
    "Uzbekistan": ["Uzbekistan"],
    "Vanuatu": ["Vanuatu"],
    "Vatican City": ["Vatican City"],
    "Venezuela": ["Venezuela"],
    "Vietnam": ["Vietnam"],
    "Wallis & Futuna": ["Wallis & Futuna"],
    "Western Sahara": ["Western Sahara"],
    "Yemen": ["Yemen"],
    "Zambia": ["Zambia"],
    "Zimbabwe": ["Zimbabwe"],
}
