# Generated by Django 4.1.6 on 2024-05-28 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_ticketbai', '0014_config_logo_alter_invoice_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='lang',
            field=models.CharField(default='eu', max_length=3),
        ),
    ]
