""" This file is automatically generated from "mitsuba.conf" using the script
    "resources/configure.py". Please do not attempt to change it manually,
    as any changes will be overwritten."""

PYTHON_EXECUTABLE = r"C:\Users\runneradmin\AppData\Local\Temp\cibw-run-cc14oa57\cp38-win_amd64\build\venv\Scripts\python.exe"
MI_DEFAULT_VARIANT = ''
MI_VARIANTS = ['scalar_rgb', 'scalar_spectral', 'cuda_ad_rgb', 'llvm_ad_rgb']
DRJIT_VERSION_REQUIREMENT = '0.4.6'
CXX_COMPILER = 'MSVC 19.39.33523.0'
