
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-06-03T13:29:50+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "623819ef81b4118e71a4a1df4b96aa5466e6fdd3",
 "version": "0.5.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
