
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-06-04T07:53:30+0200",
 "dirty": true,
 "error": null,
 "full-revisionid": "233478c295fe2d67aeffb3e2d1a16a4160aa67ad",
 "version": "0.6.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
