from distutils.core import setup

with open("README.md", "r", encoding='utf-8') as f:
    long_description = f.read()

setup(
    name='PyDataforge',
    version='1.0.0',
    description='A package for removing sensitive information from data',
    long_description=long_description,
    long_description_content_type='text/markdown',
    author='Guipeng Wei',
    author_email='18316734738@163.com',
    url='',
    license='MIT License',
    packages=['PyDataforge'],
    platforms=["all"],
    classifiers=[
        'Intended Audience :: Developers',
        'Operating System :: OS Independent',
        'Topic :: Software Development',
        'License :: OSI Approved :: MIT License',
        'Programming Language :: Python :: 3',
    ],
    install_requires=[
        'aiosignal==1.2.0',
        'async-timeout==4.0.2',
        'attrs==22.1.0',
        'certifi==2023.7.22',
        'charset-normalizer==2.0.4',
        'colorama==0.4.6',
        'filelock==3.9.0',
        'frozenlist==1.3.3',
        'fsspec==2023.4.0',
        'future==0.18.3',
        'idna==3.4',
        'imbalanced-learn==0.10.1',
        'importlib-metadata==6.0.0',
        'joblib==1.2.0',
        'mpmath==1.3.0',
        'multidict==6.0.4',
        'networkx==3.1',
        'pyasn1==0.4.8',
        'pyasn1-modules==0.2.8',
        'requests==2.31.0',
        'scikit-learn==1.3.0',
        'scipy==1.11.1',
        'six==1.16.0',
        'sympy==1.11.1',
        'threadpoolctl==2.2.0',
        'tqdm==4.65.0',
        'typing-extensions==4.7.1',
        'wrapt==1.14.1',
        'yarl==1.9.3',
        'zipp==3.11.0',
        'pandas==1.5.3',
    ],
)
