
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-06-06T14:53:46-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "4d70aefb41ca878e5beae8636955943d2634e7f6",
 "version": "3.0.0rc2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
