# Generated by Django 4.1.6 on 2023-07-05 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("serial_code", models.CharField(max_length=255)),
                ("num", models.IntegerField()),
                ("description", models.CharField(max_length=255)),
                ("simplified", models.CharField(default="01", max_length=2)),
                ("substitution", models.CharField(default="N", max_length=2)),
                ("vat_regime", models.CharField(default="N", max_length=2)),
                ("expedition_date", models.DateField()),
                ("expedition_time", models.TimeField()),
                ("transaction_date", models.DateField()),
            ],
            options={
                "verbose_name": "Invoice",
                "verbose_name_plural": "Invoices",
            },
        ),
    ]
