# Generated by Django 4.1.6 on 2023-07-06 13:26

from django.db import migrations, models
import django_ticketbai.validators


class Migration(migrations.Migration):

    dependencies = [
        ("django_ticketbai", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="pdf",
            field=models.FileField(
                null=True,
                upload_to="ticketbai",
                validators=[
                    django_ticketbai.validators.validate_pdf_extension
                ],
                verbose_name="PDF file",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="signedxml",
            field=models.TextField(blank=True, null=True),
        ),
    ]
