# Generated by Django 4.1.6 on 2023-07-07 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_ticketbai", "0007_invoice_errorxml"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invoice",
            name="user",
        ),
        migrations.AddField(
            model_name="invoice",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
