# Generated by Django 4.1.6 on 2023-07-27 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_ticketbai", "0010_alter_invoice_signature_value"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="signature_value",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Signature Value"
            ),
        ),
    ]
