from _typeshed import Incomplete
from edgeiq._utils import JsonFile as JsonFile

CREDENTIALS_DIR: Incomplete
CREDENTIALS_PATH: Incomplete
DEVICE_CONFIG_PATH: Incomplete
DEV_HOST_CONFIG_PATH: Incomplete
SYSTEM_ID_OPTIONS: Incomplete

class CredentialsFile(JsonFile):
    def __init__(self) -> None: ...
    @property
    def device_uuid(self) -> str | None: ...
    @property
    def device_refresh_token(self) -> str | None: ...
    @property
    def device_id_token(self) -> str | None: ...
    def get_dev_host_refresh_token(self, user_pool_client_id) -> str | None: ...
    def get_dev_host_id_token(self, user_pool_client_id) -> str | None: ...

def validate_system_id(system_id): ...

class DeviceConfigFile(JsonFile):
    def __init__(self) -> None: ...
    @property
    def system_id(self) -> str | None: ...
    @property
    def device_uuid(self) -> str | None: ...

class DevHostConfigFile(JsonFile):
    def __init__(self) -> None: ...
    @property
    def system_id(self) -> str | None: ...
