
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-06-04T05:02:41-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "9a66241f936544cb368c2cfe4169c27a33fe425c",
 "version": "5.4.39"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
