
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-06-03T20:56:30-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "5c0541441ee37fce16df775f6954d39912f2a598",
 "version": "2024.6.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
