# coding: utf-8

"""
    Command Center operations

    Command Center operations  # noqa: E501

    OpenAPI spec version: 23.09-sp1
    Contact: support@zadarastorage.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import CommandCenter
from CommandCenter.models.inline_response200120_vpsa_upload_endpoints import InlineResponse200120VpsaUploadEndpoints  # noqa: E501
from CommandCenter.rest import ApiException


class TestInlineResponse200120VpsaUploadEndpoints(unittest.TestCase):
    """InlineResponse200120VpsaUploadEndpoints unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse200120VpsaUploadEndpoints(self):
        """Test InlineResponse200120VpsaUploadEndpoints"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CommandCenter.models.inline_response200120_vpsa_upload_endpoints.InlineResponse200120VpsaUploadEndpoints()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
