# coding: utf-8

"""
    Command Center operations

    Command Center operations  # noqa: E501

    OpenAPI spec version: 23.09-sp1
    Contact: support@zadarastorage.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import CommandCenter
from CommandCenter.models.inline_response20082_message_data import InlineResponse20082MessageData  # noqa: E501
from CommandCenter.rest import ApiException


class TestInlineResponse20082MessageData(unittest.TestCase):
    """InlineResponse20082MessageData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20082MessageData(self):
        """Test InlineResponse20082MessageData"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CommandCenter.models.inline_response20082_message_data.InlineResponse20082MessageData()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
