# coding: utf-8

"""
    Command Center operations

    Command Center operations  # noqa: E501

    OpenAPI spec version: 23.09-sp1
    Contact: support@zadarastorage.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import CommandCenter
from CommandCenter.models.inline_response200101_virtual_networks import InlineResponse200101VirtualNetworks  # noqa: E501
from CommandCenter.rest import ApiException


class TestInlineResponse200101VirtualNetworks(unittest.TestCase):
    """InlineResponse200101VirtualNetworks unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse200101VirtualNetworks(self):
        """Test InlineResponse200101VirtualNetworks"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CommandCenter.models.inline_response200101_virtual_networks.InlineResponse200101VirtualNetworks()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
