# coding: utf-8

"""
    Command Center operations

    Command Center operations  # noqa: E501

    OpenAPI spec version: 23.09-sp1
    Contact: support@zadarastorage.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import CommandCenter
from CommandCenter.models.inline_response20082_message_actions import InlineResponse20082MessageActions  # noqa: E501
from CommandCenter.rest import ApiException


class TestInlineResponse20082MessageActions(unittest.TestCase):
    """InlineResponse20082MessageActions unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20082MessageActions(self):
        """Test InlineResponse20082MessageActions"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CommandCenter.models.inline_response20082_message_actions.InlineResponse20082MessageActions()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
