# coding: utf-8

"""
    Command Center operations

    Command Center operations  # noqa: E501

    OpenAPI spec version: 23.09-sp1
    Contact: support@zadarastorage.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import CommandCenter
from CommandCenter.models.inline_response200102_capacity_trend_dates import InlineResponse200102CapacityTrendDates  # noqa: E501
from CommandCenter.rest import ApiException


class TestInlineResponse200102CapacityTrendDates(unittest.TestCase):
    """InlineResponse200102CapacityTrendDates unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse200102CapacityTrendDates(self):
        """Test InlineResponse200102CapacityTrendDates"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CommandCenter.models.inline_response200102_capacity_trend_dates.InlineResponse200102CapacityTrendDates()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
