# coding: utf-8

"""
    Command Center operations

    Command Center operations  # noqa: E501

    OpenAPI spec version: 23.09-sp1
    Contact: support@zadarastorage.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import CommandCenter
from CommandCenter.models.inline_response200100_compatible_virtual_networks import InlineResponse200100CompatibleVirtualNetworks  # noqa: E501
from CommandCenter.rest import ApiException


class TestInlineResponse200100CompatibleVirtualNetworks(unittest.TestCase):
    """InlineResponse200100CompatibleVirtualNetworks unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse200100CompatibleVirtualNetworks(self):
        """Test InlineResponse200100CompatibleVirtualNetworks"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CommandCenter.models.inline_response200100_compatible_virtual_networks.InlineResponse200100CompatibleVirtualNetworks()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
