# generated by datamodel-codegen:
#   filename:  box.json
#   timestamp: 2024-06-04T19:41:10+00:00

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field

from . import placement


class IBox(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    Length: float = Field(..., description='The length of the box')
    Width: float = Field(..., description='The width of the box')
    Height: float = Field(..., description='The height of the box')
    Placement: placement.Model
