
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-06-05T14:55:27+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "6dd55bcfa997c952e0ad0fae959a772211c97a3b",
 "version": "6.25.15"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
